/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness/readiness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service identity and version */
        get: operations["ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate an account and list its profiles */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List devices in the current account (the Fleet) */
        get: operations["listDevices"];
        put?: never;
        /**
         * Register a device for a profile and issue a device token
         * @description Re-authenticates with account credentials and binds a new device to the
         *     chosen profile, returning a bearer token used for all subsequent calls.
         */
        post: operations["registerDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/devices/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a device token ("retire from the Fleet") */
        delete: operations["revokeDevice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve the current (account, profile, device) from the token */
        get: operations["getCurrentSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/libraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the account's libraries */
        get: operations["listLibraries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/libraries/{libraryId}/movies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse movies in a library */
        get: operations["listMovies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/libraries/{libraryId}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse series in a library */
        get: operations["listSeries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{seriesId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Series detail with seasons and episodes */
        get: operations["getSeries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Media item detail with effective metadata */
        get: operations["getMediaItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        PingResponse: {
            /** @example argosy */
            service: string;
            /** @example ok */
            status: string;
            /** @example dev */
            version: string;
        };
        /** @enum {string} */
        Role: "admin" | "viewer";
        Account: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        UserProfile: {
            /** Format: uuid */
            id: string;
            name: string;
            role: components["schemas"]["Role"];
        };
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        LoginResponse: {
            account: components["schemas"]["Account"];
            profiles: components["schemas"]["UserProfile"][];
        };
        DeviceRegistrationRequest: {
            username: string;
            /** Format: password */
            password: string;
            /**
             * Format: uuid
             * @description The profile this device is bound to.
             */
            userId: string;
            deviceName: string;
        };
        Device: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            userId: string | null;
            /** Format: date-time */
            lastSeenAt?: string | null;
            revoked: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        DeviceRegistrationResponse: {
            device: components["schemas"]["Device"];
            /** @description Bearer token for this device. */
            token: string;
        };
        Session: {
            /** Format: uuid */
            accountId: string;
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            deviceId: string;
            role: components["schemas"]["Role"];
        };
        Library: {
            /** Format: uuid */
            id: string;
            name: string;
            kind: string;
        };
        MediaItemSummary: {
            /** Format: uuid */
            id: string;
            kind: string;
            title: string;
            year?: number | null;
            posterUrl?: string | null;
        };
        MediaItemDetail: {
            /** Format: uuid */
            id: string;
            kind: string;
            title: string;
            year?: number | null;
            overview?: string | null;
            genres?: string[];
            posterUrl?: string | null;
            durationSeconds?: number | null;
            container?: string | null;
            filePath: string;
            reviewRequired: boolean;
        };
        MediaItemPage: {
            items: components["schemas"]["MediaItemSummary"][];
            total: number;
            limit: number;
            offset: number;
        };
        SeriesSummary: {
            /** Format: uuid */
            id: string;
            title: string;
            year?: number | null;
            posterUrl?: string | null;
        };
        SeriesPage: {
            items: components["schemas"]["SeriesSummary"][];
            total: number;
            limit: number;
            offset: number;
        };
        EpisodeSummary: {
            /** Format: uuid */
            id: string;
            episodeNumber: number;
            title?: string | null;
            /** Format: uuid */
            mediaItemId?: string | null;
        };
        SeasonSummary: {
            /** Format: uuid */
            id: string;
            seasonNumber: number;
            title?: string | null;
            episodes: components["schemas"]["EpisodeSummary"][];
        };
        SeriesDetail: {
            /** Format: uuid */
            id: string;
            title: string;
            year?: number | null;
            overview?: string | null;
            posterUrl?: string | null;
            seasons: components["schemas"]["SeasonSummary"][];
        };
    };
    responses: {
        /** @description Missing or invalid credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authenticated but not allowed */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description A dependency (e.g. the database) is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PingResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated; returns the account and its profiles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    registerDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceRegistrationRequest"];
            };
        };
        responses: {
            /** @description Device registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceRegistrationResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    revokeDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getCurrentSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listLibraries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Library"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listMovies: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                sort?: "title" | "added" | "year";
            };
            header?: never;
            path: {
                libraryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaItemPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listSeries: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                sort?: "title" | "year";
            };
            header?: never;
            path: {
                libraryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getSeries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seriesId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getMediaItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaItemDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
