//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for FacetType.
const (
	Genre FacetType = "genre"
	Tag   FacetType = "tag"
)

// Valid indicates whether the value is a known member of the FacetType enum.
func (e FacetType) Valid() bool {
	switch e {
	case Genre:
		return true
	case Tag:
		return true
	default:
		return false
	}
}

// Defines values for PlaybackInfoMethod.
const (
	PlaybackInfoMethodDirect    PlaybackInfoMethod = "direct"
	PlaybackInfoMethodRemux     PlaybackInfoMethod = "remux"
	PlaybackInfoMethodTranscode PlaybackInfoMethod = "transcode"
)

// Valid indicates whether the value is a known member of the PlaybackInfoMethod enum.
func (e PlaybackInfoMethod) Valid() bool {
	switch e {
	case PlaybackInfoMethodDirect:
		return true
	case PlaybackInfoMethodRemux:
		return true
	case PlaybackInfoMethodTranscode:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	Admin  Role = "admin"
	Viewer Role = "viewer"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case Admin:
		return true
	case Viewer:
		return true
	default:
		return false
	}
}

// Defines values for SubtitleTrackSource.
const (
	Embedded      SubtitleTrackSource = "embedded"
	Opensubtitles SubtitleTrackSource = "opensubtitles"
)

// Valid indicates whether the value is a known member of the SubtitleTrackSource enum.
func (e SubtitleTrackSource) Valid() bool {
	switch e {
	case Embedded:
		return true
	case Opensubtitles:
		return true
	default:
		return false
	}
}

// Defines values for TranscodeSessionMethod.
const (
	TranscodeSessionMethodRemux     TranscodeSessionMethod = "remux"
	TranscodeSessionMethodTranscode TranscodeSessionMethod = "transcode"
)

// Valid indicates whether the value is a known member of the TranscodeSessionMethod enum.
func (e TranscodeSessionMethod) Valid() bool {
	switch e {
	case TranscodeSessionMethodRemux:
		return true
	case TranscodeSessionMethodTranscode:
		return true
	default:
		return false
	}
}

// Defines values for TranscodeSessionState.
const (
	Complete TranscodeSessionState = "complete"
	Failed   TranscodeSessionState = "failed"
	Running  TranscodeSessionState = "running"
	Starting TranscodeSessionState = "starting"
	Stopped  TranscodeSessionState = "stopped"
)

// Valid indicates whether the value is a known member of the TranscodeSessionState enum.
func (e TranscodeSessionState) Valid() bool {
	switch e {
	case Complete:
		return true
	case Failed:
		return true
	case Running:
		return true
	case Starting:
		return true
	case Stopped:
		return true
	default:
		return false
	}
}

// Defines values for ListMoviesParamsSort.
const (
	ListMoviesParamsSortAdded  ListMoviesParamsSort = "added"
	ListMoviesParamsSortRating ListMoviesParamsSort = "rating"
	ListMoviesParamsSortTitle  ListMoviesParamsSort = "title"
	ListMoviesParamsSortYear   ListMoviesParamsSort = "year"
)

// Valid indicates whether the value is a known member of the ListMoviesParamsSort enum.
func (e ListMoviesParamsSort) Valid() bool {
	switch e {
	case ListMoviesParamsSortAdded:
		return true
	case ListMoviesParamsSortRating:
		return true
	case ListMoviesParamsSortTitle:
		return true
	case ListMoviesParamsSortYear:
		return true
	default:
		return false
	}
}

// Defines values for ListMoviesParamsWatched.
const (
	ListMoviesParamsWatchedInProgress ListMoviesParamsWatched = "in_progress"
	ListMoviesParamsWatchedUnwatched  ListMoviesParamsWatched = "unwatched"
	ListMoviesParamsWatchedWatched    ListMoviesParamsWatched = "watched"
)

// Valid indicates whether the value is a known member of the ListMoviesParamsWatched enum.
func (e ListMoviesParamsWatched) Valid() bool {
	switch e {
	case ListMoviesParamsWatchedInProgress:
		return true
	case ListMoviesParamsWatchedUnwatched:
		return true
	case ListMoviesParamsWatchedWatched:
		return true
	default:
		return false
	}
}

// Defines values for ListSeriesParamsSort.
const (
	ListSeriesParamsSortRating ListSeriesParamsSort = "rating"
	ListSeriesParamsSortTitle  ListSeriesParamsSort = "title"
	ListSeriesParamsSortYear   ListSeriesParamsSort = "year"
)

// Valid indicates whether the value is a known member of the ListSeriesParamsSort enum.
func (e ListSeriesParamsSort) Valid() bool {
	switch e {
	case ListSeriesParamsSortRating:
		return true
	case ListSeriesParamsSortTitle:
		return true
	case ListSeriesParamsSortYear:
		return true
	default:
		return false
	}
}

// Defines values for ListSeriesParamsWatched.
const (
	ListSeriesParamsWatchedInProgress ListSeriesParamsWatched = "in_progress"
	ListSeriesParamsWatchedUnwatched  ListSeriesParamsWatched = "unwatched"
	ListSeriesParamsWatchedWatched    ListSeriesParamsWatched = "watched"
)

// Valid indicates whether the value is a known member of the ListSeriesParamsWatched enum.
func (e ListSeriesParamsWatched) Valid() bool {
	switch e {
	case ListSeriesParamsWatchedInProgress:
		return true
	case ListSeriesParamsWatchedUnwatched:
		return true
	case ListSeriesParamsWatchedWatched:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// ContinueItem defines model for ContinueItem.
type ContinueItem struct {
	// BackdropUrl Landscape backdrop for full-screen heroes; falls back to posterUrl.
	BackdropUrl     *string             `json:"backdropUrl,omitempty"`
	DurationSeconds *float32            `json:"durationSeconds,omitempty"`
	Id              openapi_types.UUID  `json:"id"`
	Kind            string              `json:"kind"`
	Percent         float32             `json:"percent"`
	PositionSeconds float32             `json:"positionSeconds"`
	PosterUrl       *string             `json:"posterUrl,omitempty"`
	SeriesId        *openapi_types.UUID `json:"seriesId,omitempty"`
	SeriesTitle     *string             `json:"seriesTitle,omitempty"`
	Title           string              `json:"title"`
	Year            *int                `json:"year,omitempty"`
}

// Device defines model for Device.
type Device struct {
	CreatedAt  time.Time          `json:"createdAt"`
	Id         openapi_types.UUID `json:"id"`
	LastSeenAt *time.Time         `json:"lastSeenAt,omitempty"`
	Name       string             `json:"name"`

	// Platform Client platform/type label captured at registration.
	Platform *string             `json:"platform,omitempty"`
	Revoked  bool                `json:"revoked"`
	UserId   *openapi_types.UUID `json:"userId"`

	// UserName Display name of the profile this device is bound to (the Fleet shows whose device it is).
	UserName *string `json:"userName,omitempty"`
}

// DevicePreferences defines model for DevicePreferences.
type DevicePreferences struct {
	// AudioLanguage Preferred audio language (ISO code). Persisted; applied once audio-track selection ships.
	AudioLanguage *string `json:"audioLanguage,omitempty"`

	// SubtitleEnabled Whether subtitles are on by default.
	SubtitleEnabled bool `json:"subtitleEnabled"`

	// SubtitleLanguage Preferred subtitle language (ISO code); the player auto-selects a matching track.
	SubtitleLanguage *string `json:"subtitleLanguage,omitempty"`
}

// DeviceRegistrationRequest defines model for DeviceRegistrationRequest.
type DeviceRegistrationRequest struct {
	DeviceName string `json:"deviceName"`
	Password   string `json:"password"`

	// Platform Client platform/type label (e.g. "web", "tv", "phone"); shown in the Fleet.
	Platform *string `json:"platform,omitempty"`

	// UserId The profile this device is bound to.
	UserId   openapi_types.UUID `json:"userId"`
	Username string             `json:"username"`
}

// DeviceRegistrationResponse defines model for DeviceRegistrationResponse.
type DeviceRegistrationResponse struct {
	Device Device `json:"device"`

	// Token Bearer token for this device.
	Token string `json:"token"`
}

// DeviceRenameRequest defines model for DeviceRenameRequest.
type DeviceRenameRequest struct {
	Name string `json:"name"`
}

// EpisodeSummary defines model for EpisodeSummary.
type EpisodeSummary struct {
	DurationSeconds *float32            `json:"durationSeconds,omitempty"`
	EpisodeNumber   int                 `json:"episodeNumber"`
	Id              openapi_types.UUID  `json:"id"`
	MediaItemId     *openapi_types.UUID `json:"mediaItemId,omitempty"`

	// PositionSeconds Current profile's resume position.
	PositionSeconds *float32 `json:"positionSeconds,omitempty"`
	Title           *string  `json:"title,omitempty"`
	Watched         *bool    `json:"watched,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Facet defines model for Facet.
type Facet struct {
	// Count Number of films + series carrying it.
	Count int `json:"count"`

	// Type Which dimension the value belongs to.
	Type  FacetType `json:"type"`
	Value string    `json:"value"`
}

// FacetType Which dimension the value belongs to.
type FacetType string

// Library defines model for Library.
type Library struct {
	Id   openapi_types.UUID `json:"id"`
	Kind string             `json:"kind"`
	Name string             `json:"name"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Account  Account       `json:"account"`
	Profiles []UserProfile `json:"profiles"`
}

// MediaItemDetail defines model for MediaItemDetail.
type MediaItemDetail struct {
	// BackdropUrl Landscape backdrop for full-screen heroes; falls back to posterUrl.
	BackdropUrl     *string            `json:"backdropUrl,omitempty"`
	Container       *string            `json:"container,omitempty"`
	DurationSeconds *float32           `json:"durationSeconds,omitempty"`
	FilePath        string             `json:"filePath"`
	Genres          *[]string          `json:"genres,omitempty"`
	Id              openapi_types.UUID `json:"id"`
	Kind            string             `json:"kind"`
	Overview        *string            `json:"overview,omitempty"`
	PosterUrl       *string            `json:"posterUrl,omitempty"`

	// Rating Effective provider rating, 0–10.
	Rating         *float32 `json:"rating,omitempty"`
	ReviewRequired bool     `json:"reviewRequired"`
	Tags           []string `json:"tags"`
	Title          string   `json:"title"`
	Year           *int     `json:"year,omitempty"`
}

// MediaItemPage defines model for MediaItemPage.
type MediaItemPage struct {
	Items  []MediaItemSummary `json:"items"`
	Limit  int                `json:"limit"`
	Offset int                `json:"offset"`
	Total  int                `json:"total"`
}

// MediaItemSummary defines model for MediaItemSummary.
type MediaItemSummary struct {
	// BackdropUrl Landscape backdrop for full-screen heroes; falls back to posterUrl.
	BackdropUrl *string            `json:"backdropUrl,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Kind        string             `json:"kind"`
	PosterUrl   *string            `json:"posterUrl,omitempty"`

	// Rating Effective provider rating, 0–10.
	Rating *float32 `json:"rating,omitempty"`
	Tags   []string `json:"tags"`
	Title  string   `json:"title"`
	Year   *int     `json:"year,omitempty"`
}

// PingResponse defines model for PingResponse.
type PingResponse struct {
	Service string `json:"service"`
	Status  string `json:"status"`
	Version string `json:"version"`
}

// PlayState defines model for PlayState.
type PlayState struct {
	DurationSeconds *float32   `json:"durationSeconds,omitempty"`
	PositionSeconds float32    `json:"positionSeconds"`
	UpdatedAt       *time.Time `json:"updatedAt,omitempty"`
	Watched         bool       `json:"watched"`
}

// PlaybackInfo defines model for PlaybackInfo.
type PlaybackInfo struct {
	AudioCodec *string `json:"audioCodec,omitempty"`
	Container  string  `json:"container"`
	DirectPlay bool    `json:"directPlay"`

	// Method Cheapest playable path — serve as-is, repackage (copy codecs), or re-encode.
	Method     PlaybackInfoMethod `json:"method"`
	Reason     *string            `json:"reason,omitempty"`
	VideoCodec *string            `json:"videoCodec,omitempty"`
}

// PlaybackInfoMethod Cheapest playable path — serve as-is, repackage (copy codecs), or re-encode.
type PlaybackInfoMethod string

// PlaybackSession defines model for PlaybackSession.
type PlaybackSession struct {
	DeviceId        openapi_types.UUID `json:"deviceId"`
	DurationSeconds *float64           `json:"durationSeconds,omitempty"`

	// Encoder Encoder of the owned transcode session, if any.
	Encoder  *string            `json:"encoder,omitempty"`
	ItemId   openapi_types.UUID `json:"itemId"`
	LastSeen time.Time          `json:"lastSeen"`

	// Method remux | transcode, if this session owns a transcode session.
	Method          *string   `json:"method,omitempty"`
	PositionSeconds float64   `json:"positionSeconds"`
	StartedAt       time.Time `json:"startedAt"`

	// State e.g. "playing"
	State  string             `json:"state"`
	UserId openapi_types.UUID `json:"userId"`
}

// ProgressUpdate defines model for ProgressUpdate.
type ProgressUpdate struct {
	DurationSeconds *float32 `json:"durationSeconds,omitempty"`
	PositionSeconds float32  `json:"positionSeconds"`
}

// Role defines model for Role.
type Role string

// ScanLibraryResult defines model for ScanLibraryResult.
type ScanLibraryResult struct {
	Error     *string            `json:"error,omitempty"`
	Errors    int                `json:"errors"`
	LibraryId openapi_types.UUID `json:"libraryId"`
	Name      string             `json:"name"`
	Scanned   int                `json:"scanned"`
}

// ScanStatus defines model for ScanStatus.
type ScanStatus struct {
	FinishedAt *time.Time          `json:"finishedAt,omitempty"`
	Libraries  []ScanLibraryResult `json:"libraries"`
	Running    bool                `json:"running"`
	StartedAt  *time.Time          `json:"startedAt,omitempty"`
}

// SearchResults defines model for SearchResults.
type SearchResults struct {
	Movies []MediaItemSummary `json:"movies"`
	Series []SeriesSummary    `json:"series"`
}

// SeasonSummary defines model for SeasonSummary.
type SeasonSummary struct {
	Episodes     []EpisodeSummary   `json:"episodes"`
	Id           openapi_types.UUID `json:"id"`
	SeasonNumber int                `json:"seasonNumber"`
	Title        *string            `json:"title,omitempty"`
}

// SeriesDetail defines model for SeriesDetail.
type SeriesDetail struct {
	// BackdropUrl Landscape backdrop for full-screen heroes; falls back to posterUrl.
	BackdropUrl *string            `json:"backdropUrl,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Overview    *string            `json:"overview,omitempty"`
	PosterUrl   *string            `json:"posterUrl,omitempty"`
	Seasons     []SeasonSummary    `json:"seasons"`
	Tags        []string           `json:"tags"`
	Title       string             `json:"title"`
	Year        *int               `json:"year,omitempty"`
}

// SeriesPage defines model for SeriesPage.
type SeriesPage struct {
	Items  []SeriesSummary `json:"items"`
	Limit  int             `json:"limit"`
	Offset int             `json:"offset"`
	Total  int             `json:"total"`
}

// SeriesSummary defines model for SeriesSummary.
type SeriesSummary struct {
	// BackdropUrl Landscape backdrop for full-screen heroes; falls back to posterUrl.
	BackdropUrl *string            `json:"backdropUrl,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	PosterUrl   *string            `json:"posterUrl,omitempty"`

	// Rating Effective provider rating, 0–10.
	Rating *float32 `json:"rating,omitempty"`
	Tags   []string `json:"tags"`
	Title  string   `json:"title"`
	Year   *int     `json:"year,omitempty"`
}

// Session defines model for Session.
type Session struct {
	AccountId openapi_types.UUID `json:"accountId"`
	DeviceId  openapi_types.UUID `json:"deviceId"`
	Role      Role               `json:"role"`
	UserId    openapi_types.UUID `json:"userId"`
}

// SubtitleTrack defines model for SubtitleTrack.
type SubtitleTrack struct {
	Default bool `json:"default"`
	Forced  bool `json:"forced"`

	// Id Track handle for the WebVTT endpoint (e.g. "embedded:3", "os:12345").
	Id string `json:"id"`

	// Label Human-readable label for the subtitle picker.
	Label string `json:"label"`

	// Language BCP-47 language code (e.g. "en"), or "und" when unknown.
	Language string              `json:"language"`
	Source   SubtitleTrackSource `json:"source"`
}

// SubtitleTrackSource defines model for SubtitleTrack.Source.
type SubtitleTrackSource string

// TranscodeCacheStats defines model for TranscodeCacheStats.
type TranscodeCacheStats struct {
	BudgetBytes int64 `json:"budgetBytes"`
	LiveDirs    int   `json:"liveDirs"`
	SessionDirs int   `json:"sessionDirs"`
	TotalBytes  int64 `json:"totalBytes"`
}

// TranscodeCapabilities defines model for TranscodeCapabilities.
type TranscodeCapabilities struct {
	// Available Encoder backends usable on this host (always includes "software").
	Available []string `json:"available"`

	// Selected The encoder chosen by the configured preference order.
	Selected string `json:"selected"`
}

// TranscodeProgress defines model for TranscodeProgress.
type TranscodeProgress struct {
	Fps float64 `json:"fps"`

	// OutTimeMs Encoded timeline position in milliseconds.
	OutTimeMs int64 `json:"outTimeMs"`

	// Speed Encode speed as a multiple of realtime (2.5 == 2.5x).
	Speed float64 `json:"speed"`
}

// TranscodeSession defines model for TranscodeSession.
type TranscodeSession struct {
	Encoder string             `json:"encoder"`
	Error   *string            `json:"error,omitempty"`
	Id      string             `json:"id"`
	ItemId  openapi_types.UUID `json:"itemId"`

	// Method Whether this session copies codecs (remux) or re-encodes (transcode).
	Method TranscodeSessionMethod `json:"method"`

	// PlaylistUrl Relative URL of the HLS media playlist for this session.
	PlaylistUrl string                `json:"playlistUrl"`
	Progress    TranscodeProgress     `json:"progress"`
	StartAt     float64               `json:"startAt"`
	StartedAt   time.Time             `json:"startedAt"`
	State       TranscodeSessionState `json:"state"`
}

// TranscodeSessionMethod Whether this session copies codecs (remux) or re-encodes (transcode).
type TranscodeSessionMethod string

// TranscodeSessionState defines model for TranscodeSession.State.
type TranscodeSessionState string

// TranscodeStartRequest defines model for TranscodeStartRequest.
type TranscodeStartRequest struct {
	// Hevc Whether the client can play HEVC (H.265) in fMP4/MSE — detected via MediaSource.isTypeSupported. When true, an HEVC source is remuxed (copied) at native resolution including 4K instead of being re-encoded to H.264 1080p, and re-encodes of >1080p sources target HEVC. Defaults to false (H.264 only).
	Hevc *bool `json:"hevc,omitempty"`

	// StartAt Seek offset in seconds (default 0).
	StartAt *float64 `json:"startAt,omitempty"`
}

// UserProfile defines model for UserProfile.
type UserProfile struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
	Role Role               `json:"role"`
}

// WatchedUpdate defines model for WatchedUpdate.
type WatchedUpdate struct {
	Watched bool `json:"watched"`
}

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// BeaconStreamParams defines parameters for BeaconStream.
type BeaconStreamParams struct {
	// Token Per-device bearer token (EventSource can't set headers).
	Token *string `form:"token,omitempty" json:"token,omitempty"`
}

// ListFacetsParams defines parameters for ListFacets.
type ListFacetsParams struct {
	// Limit Max facets to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// StreamItemParams defines parameters for StreamItem.
type StreamItemParams struct {
	// Token Per-device token (alternative to the bearer header).
	Token *string `form:"token,omitempty" json:"token,omitempty"`
}

// GetSubtitleParams defines parameters for GetSubtitle.
type GetSubtitleParams struct {
	// Token Per-device token (alternative to the bearer header).
	Token *string `form:"token,omitempty" json:"token,omitempty"`
}

// ListMoviesParams defines parameters for ListMovies.
type ListMoviesParams struct {
	Limit  *int                  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int                  `form:"offset,omitempty" json:"offset,omitempty"`
	Sort   *ListMoviesParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Tag Filter to items carrying this label/tag (e.g. anime).
	Tag *string `form:"tag,omitempty" json:"tag,omitempty"`

	// Genre Filter to items in any of these genres (repeatable).
	Genre *[]string `form:"genre,omitempty" json:"genre,omitempty"`

	// RatingMin Minimum effective rating (0–10).
	RatingMin *float32 `form:"rating_min,omitempty" json:"rating_min,omitempty"`

	// Watched Per-user watched state.
	Watched *ListMoviesParamsWatched `form:"watched,omitempty" json:"watched,omitempty"`

	// YearFrom Earliest release year (inclusive).
	YearFrom *int `form:"year_from,omitempty" json:"year_from,omitempty"`

	// YearTo Latest release year (inclusive).
	YearTo *int `form:"year_to,omitempty" json:"year_to,omitempty"`
}

// ListMoviesParamsSort defines parameters for ListMovies.
type ListMoviesParamsSort string

// ListMoviesParamsWatched defines parameters for ListMovies.
type ListMoviesParamsWatched string

// ListSeriesParams defines parameters for ListSeries.
type ListSeriesParams struct {
	Limit  *int                  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int                  `form:"offset,omitempty" json:"offset,omitempty"`
	Sort   *ListSeriesParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Tag Filter to series carrying this label/tag (e.g. anime).
	Tag *string `form:"tag,omitempty" json:"tag,omitempty"`

	// Genre Filter to series in any of these genres (repeatable).
	Genre *[]string `form:"genre,omitempty" json:"genre,omitempty"`

	// RatingMin Minimum effective rating (0–10).
	RatingMin *float32 `form:"rating_min,omitempty" json:"rating_min,omitempty"`

	// Watched Per-user watched state (aggregated over episodes).
	Watched *ListSeriesParamsWatched `form:"watched,omitempty" json:"watched,omitempty"`

	// YearFrom Earliest release year (inclusive).
	YearFrom *int `form:"year_from,omitempty" json:"year_from,omitempty"`

	// YearTo Latest release year (inclusive).
	YearTo *int `form:"year_to,omitempty" json:"year_to,omitempty"`
}

// ListSeriesParamsSort defines parameters for ListSeries.
type ListSeriesParamsSort string

// ListSeriesParamsWatched defines parameters for ListSeries.
type ListSeriesParamsWatched string

// ListRecentParams defines parameters for ListRecent.
type ListRecentParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// SearchParams defines parameters for Search.
type SearchParams struct {
	// Q Search text (prefix-matched per token).
	Q string `form:"q" json:"q"`

	// Limit Max results per group.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// RegisterDeviceJSONRequestBody defines body for RegisterDevice for application/json ContentType.
type RegisterDeviceJSONRequestBody = DeviceRegistrationRequest

// RenameDeviceJSONRequestBody defines body for RenameDevice for application/json ContentType.
type RenameDeviceJSONRequestBody = DeviceRenameRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ReportProgressJSONRequestBody defines body for ReportProgress for application/json ContentType.
type ReportProgressJSONRequestBody = ProgressUpdate

// StartTranscodeJSONRequestBody defines body for StartTranscode for application/json ContentType.
type StartTranscodeJSONRequestBody = TranscodeStartRequest

// SetWatchedJSONRequestBody defines body for SetWatched for application/json ContentType.
type SetWatchedJSONRequestBody = WatchedUpdate

// SetDevicePreferencesJSONRequestBody defines body for SetDevicePreferences for application/json ContentType.
type SetDevicePreferencesJSONRequestBody = DevicePreferences

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List devices in the current account (the Fleet)
	// (GET /api/v1/auth/devices)
	ListDevices(w http.ResponseWriter, r *http.Request)
	// Register a device for a profile and issue a device token
	// (POST /api/v1/auth/devices)
	RegisterDevice(w http.ResponseWriter, r *http.Request)
	// Revoke a device token ("retire from the Fleet")
	// (DELETE /api/v1/auth/devices/{deviceId})
	RevokeDevice(w http.ResponseWriter, r *http.Request, deviceId openapi_types.UUID)
	// Rename a device in the Fleet
	// (PATCH /api/v1/auth/devices/{deviceId})
	RenameDevice(w http.ResponseWriter, r *http.Request, deviceId openapi_types.UUID)
	// Authenticate an account and list its profiles
	// (POST /api/v1/auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Resolve the current (account, profile, device) from the token
	// (GET /api/v1/auth/me)
	GetCurrentSession(w http.ResponseWriter, r *http.Request)
	// SSE stream of the current user's live play-state events (Beacon)
	// (GET /api/v1/beacon)
	BeaconStream(w http.ResponseWriter, r *http.Request, params BeaconStreamParams)
	// Continue-watching / on-deck items for the current profile
	// (GET /api/v1/continue)
	ListContinue(w http.ResponseWriter, r *http.Request)
	// Most common facets (genres + tags) across the account's manifest
	// (GET /api/v1/facets)
	ListFacets(w http.ResponseWriter, r *http.Request, params ListFacetsParams)
	// Media item detail with effective metadata
	// (GET /api/v1/items/{itemId})
	GetMediaItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// Direct-play capability decision for the item
	// (GET /api/v1/items/{itemId}/playback)
	GetPlaybackInfo(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// Current play-state (resume position) for the item
	// (GET /api/v1/items/{itemId}/progress)
	GetProgress(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// Heartbeat — upsert the resume position for the current profile
	// (PUT /api/v1/items/{itemId}/progress)
	ReportProgress(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// Direct-play media stream with HTTP range support
	// (GET /api/v1/items/{itemId}/stream)
	StreamItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID, params StreamItemParams)
	// Available subtitle tracks for an item
	// (GET /api/v1/items/{itemId}/subtitles)
	ListSubtitles(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// A subtitle track as WebVTT
	// (GET /api/v1/items/{itemId}/subtitles/{trackId})
	GetSubtitle(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID, trackId string, params GetSubtitleParams)
	// Start (or join) an HLS transcode session for an item
	// (POST /api/v1/items/{itemId}/transcode)
	StartTranscode(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// Mark an item watched / unwatched for the current profile
	// (POST /api/v1/items/{itemId}/watched)
	SetWatched(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// List the account's libraries
	// (GET /api/v1/libraries)
	ListLibraries(w http.ResponseWriter, r *http.Request)
	// Browse movies in a library
	// (GET /api/v1/libraries/{libraryId}/movies)
	ListMovies(w http.ResponseWriter, r *http.Request, libraryId openapi_types.UUID, params ListMoviesParams)
	// Browse series in a library
	// (GET /api/v1/libraries/{libraryId}/series)
	ListSeries(w http.ResponseWriter, r *http.Request, libraryId openapi_types.UUID, params ListSeriesParams)
	// Service identity and version
	// (GET /api/v1/ping)
	Ping(w http.ResponseWriter, r *http.Request)
	// Get the calling device's playback preferences
	// (GET /api/v1/preferences)
	GetDevicePreferences(w http.ResponseWriter, r *http.Request)
	// Update the calling device's playback preferences
	// (PUT /api/v1/preferences)
	SetDevicePreferences(w http.ResponseWriter, r *http.Request)
	// Recently-added items (films + series) across the account
	// (GET /api/v1/recent)
	ListRecent(w http.ResponseWriter, r *http.Request, params ListRecentParams)
	// Trigger an immediate library re-scan ("rebuild the Manifest")
	// (POST /api/v1/scan)
	TriggerScan(w http.ResponseWriter, r *http.Request)
	// Current/last scan sweep status
	// (GET /api/v1/scan/status)
	GetScanStatus(w http.ResponseWriter, r *http.Request)
	// Full-text search across the account's films and series
	// (GET /api/v1/search)
	Search(w http.ResponseWriter, r *http.Request, params SearchParams)
	// Series detail with seasons and episodes
	// (GET /api/v1/series/{seriesId})
	GetSeries(w http.ResponseWriter, r *http.Request, seriesId openapi_types.UUID)
	// Live playback sessions (who's watching what, where, now)
	// (GET /api/v1/sessions)
	ListPlaybackSessions(w http.ResponseWriter, r *http.Request)
	// Transcode cache usage (Ballast)
	// (GET /api/v1/transcode/cache)
	GetTranscodeCache(w http.ResponseWriter, r *http.Request)
	// Encoders available on this host and the selected one
	// (GET /api/v1/transcode/capabilities)
	GetTranscodeCapabilities(w http.ResponseWriter, r *http.Request)
	// Live transcode sessions for the current account (The Helm)
	// (GET /api/v1/transcode/sessions)
	ListTranscodeSessions(w http.ResponseWriter, r *http.Request)
	// Stop a transcode session and purge its output
	// (DELETE /api/v1/transcode/{sessionId})
	StopTranscode(w http.ResponseWriter, r *http.Request, sessionId string)
	// HLS artifact for a session (master/variant playlist, init, or segment)
	// (GET /api/v1/transcode/{sessionId}/{file})
	GetTranscodeFile(w http.ResponseWriter, r *http.Request, sessionId string, file string)
	// Liveness/readiness probe
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListDevices operation middleware
func (siw *ServerInterfaceWrapper) ListDevices(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDevices(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterDevice operation middleware
func (siw *ServerInterfaceWrapper) RegisterDevice(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterDevice(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeDevice operation middleware
func (siw *ServerInterfaceWrapper) RevokeDevice(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "deviceId" -------------
	var deviceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "deviceId", r.PathValue("deviceId"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "deviceId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeDevice(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RenameDevice operation middleware
func (siw *ServerInterfaceWrapper) RenameDevice(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "deviceId" -------------
	var deviceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "deviceId", r.PathValue("deviceId"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "deviceId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RenameDevice(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentSession operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentSession(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BeaconStream operation middleware
func (siw *ServerInterfaceWrapper) BeaconStream(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params BeaconStreamParams

	// ------------- Optional query parameter "token" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "token", r.URL.Query(), &params.Token, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "token"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BeaconStream(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListContinue operation middleware
func (siw *ServerInterfaceWrapper) ListContinue(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListContinue(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListFacets operation middleware
func (siw *ServerInterfaceWrapper) ListFacets(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListFacetsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFacets(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMediaItem operation middleware
func (siw *ServerInterfaceWrapper) GetMediaItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMediaItem(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPlaybackInfo operation middleware
func (siw *ServerInterfaceWrapper) GetPlaybackInfo(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlaybackInfo(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProgress operation middleware
func (siw *ServerInterfaceWrapper) GetProgress(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProgress(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReportProgress operation middleware
func (siw *ServerInterfaceWrapper) ReportProgress(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReportProgress(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamItem operation middleware
func (siw *ServerInterfaceWrapper) StreamItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params StreamItemParams

	// ------------- Optional query parameter "token" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "token", r.URL.Query(), &params.Token, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "token"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamItem(w, r, itemId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSubtitles operation middleware
func (siw *ServerInterfaceWrapper) ListSubtitles(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSubtitles(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSubtitle operation middleware
func (siw *ServerInterfaceWrapper) GetSubtitle(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	// ------------- Path parameter "trackId" -------------
	var trackId string

	err = runtime.BindStyledParameterWithOptions("simple", "trackId", r.PathValue("trackId"), &trackId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "trackId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSubtitleParams

	// ------------- Optional query parameter "token" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "token", r.URL.Query(), &params.Token, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "token"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSubtitle(w, r, itemId, trackId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartTranscode operation middleware
func (siw *ServerInterfaceWrapper) StartTranscode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartTranscode(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetWatched operation middleware
func (siw *ServerInterfaceWrapper) SetWatched(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetWatched(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListLibraries operation middleware
func (siw *ServerInterfaceWrapper) ListLibraries(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLibraries(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMovies operation middleware
func (siw *ServerInterfaceWrapper) ListMovies(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "libraryId" -------------
	var libraryId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "libraryId", r.PathValue("libraryId"), &libraryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "libraryId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMoviesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tag", r.URL.Query(), &params.Tag, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tag"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "genre" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "genre", r.URL.Query(), &params.Genre, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "genre"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "genre", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "rating_min" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "rating_min", r.URL.Query(), &params.RatingMin, runtime.BindQueryParameterOptions{Type: "number", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "rating_min"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "rating_min", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "watched" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "watched", r.URL.Query(), &params.Watched, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "watched"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "watched", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "year_from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "year_from", r.URL.Query(), &params.YearFrom, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "year_from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "year_from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "year_to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "year_to", r.URL.Query(), &params.YearTo, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "year_to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "year_to", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMovies(w, r, libraryId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSeries operation middleware
func (siw *ServerInterfaceWrapper) ListSeries(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "libraryId" -------------
	var libraryId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "libraryId", r.PathValue("libraryId"), &libraryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "libraryId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSeriesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tag", r.URL.Query(), &params.Tag, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tag"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "genre" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "genre", r.URL.Query(), &params.Genre, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "genre"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "genre", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "rating_min" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "rating_min", r.URL.Query(), &params.RatingMin, runtime.BindQueryParameterOptions{Type: "number", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "rating_min"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "rating_min", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "watched" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "watched", r.URL.Query(), &params.Watched, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "watched"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "watched", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "year_from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "year_from", r.URL.Query(), &params.YearFrom, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "year_from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "year_from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "year_to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "year_to", r.URL.Query(), &params.YearTo, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "year_to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "year_to", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSeries(w, r, libraryId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Ping operation middleware
func (siw *ServerInterfaceWrapper) Ping(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Ping(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDevicePreferences operation middleware
func (siw *ServerInterfaceWrapper) GetDevicePreferences(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDevicePreferences(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetDevicePreferences operation middleware
func (siw *ServerInterfaceWrapper) SetDevicePreferences(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetDevicePreferences(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRecent operation middleware
func (siw *ServerInterfaceWrapper) ListRecent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRecentParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRecent(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerScan operation middleware
func (siw *ServerInterfaceWrapper) TriggerScan(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerScan(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetScanStatus operation middleware
func (siw *ServerInterfaceWrapper) GetScanStatus(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetScanStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Search operation middleware
func (siw *ServerInterfaceWrapper) Search(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchParams

	// ------------- Required query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Search(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSeries operation middleware
func (siw *ServerInterfaceWrapper) GetSeries(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "seriesId" -------------
	var seriesId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "seriesId", r.PathValue("seriesId"), &seriesId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "seriesId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSeries(w, r, seriesId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPlaybackSessions operation middleware
func (siw *ServerInterfaceWrapper) ListPlaybackSessions(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPlaybackSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTranscodeCache operation middleware
func (siw *ServerInterfaceWrapper) GetTranscodeCache(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTranscodeCache(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTranscodeCapabilities operation middleware
func (siw *ServerInterfaceWrapper) GetTranscodeCapabilities(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTranscodeCapabilities(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTranscodeSessions operation middleware
func (siw *ServerInterfaceWrapper) ListTranscodeSessions(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTranscodeSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopTranscode operation middleware
func (siw *ServerInterfaceWrapper) StopTranscode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId string

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopTranscode(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTranscodeFile operation middleware
func (siw *ServerInterfaceWrapper) GetTranscodeFile(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId string

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	// ------------- Path parameter "file" -------------
	var file string

	err = runtime.BindStyledParameterWithOptions("simple", "file", r.PathValue("file"), &file, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "file", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTranscodeFile(w, r, sessionId, file)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/auth/devices", wrapper.ListDevices)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/auth/devices", wrapper.RegisterDevice)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/auth/devices/{deviceId}", wrapper.RevokeDevice)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/auth/devices/{deviceId}", wrapper.RenameDevice)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/auth/login", wrapper.Login)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/auth/me", wrapper.GetCurrentSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/beacon", wrapper.BeaconStream)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/continue", wrapper.ListContinue)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/facets", wrapper.ListFacets)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/items/{itemId}", wrapper.GetMediaItem)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/items/{itemId}/playback", wrapper.GetPlaybackInfo)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/items/{itemId}/progress", wrapper.GetProgress)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/api/v1/items/{itemId}/progress", wrapper.ReportProgress)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/items/{itemId}/stream", wrapper.StreamItem)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/items/{itemId}/subtitles", wrapper.ListSubtitles)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/items/{itemId}/subtitles/{trackId}", wrapper.GetSubtitle)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/items/{itemId}/transcode", wrapper.StartTranscode)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/items/{itemId}/watched", wrapper.SetWatched)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/libraries", wrapper.ListLibraries)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/libraries/{libraryId}/movies", wrapper.ListMovies)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/libraries/{libraryId}/series", wrapper.ListSeries)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/ping", wrapper.Ping)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/preferences", wrapper.GetDevicePreferences)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/api/v1/preferences", wrapper.SetDevicePreferences)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/recent", wrapper.ListRecent)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/scan", wrapper.TriggerScan)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/scan/status", wrapper.GetScanStatus)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/search", wrapper.Search)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/series/{seriesId}", wrapper.GetSeries)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/sessions", wrapper.ListPlaybackSessions)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/transcode/cache", wrapper.GetTranscodeCache)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/transcode/capabilities", wrapper.GetTranscodeCapabilities)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/transcode/sessions", wrapper.ListTranscodeSessions)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/transcode/{sessionId}", wrapper.StopTranscode)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/transcode/{sessionId}/{file}", wrapper.GetTranscodeFile)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealth)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H3rkts21uCrnOJulaWKLu3b7GynprYcX2LvZyeubufLj8iVhsgjCdMkwACgZH3erpp32HnCeZKvcABQ",
	"pARK6m53x5lK/sQtgrgcnPuNn5NUFqUUKIxOTj8nCnUphUb645VUU55lKOwfqRQGhbH/ZGWZ85QZLsX4",
	"71rSY50usGD2X/9T4Sw5Tf7HeDPz2D3V45dKSZVcXV0Nkgx1qnhpJ0lOk2eVWaAwdlbMYFoZENIAy3O5",
	"wiy5GiQ/SPNKViK7+62coZaVSpF2MKM1rwbJT4JVZiEV/y+8hz2841pzMQepgIsly3kGqcLMQojlOrEv",
	"+DnsEs/SVFZuL6WSJSrD3QVy2upMqoKZ5DSpKp4lg8SsS0xOE20UF3N7NsEKtAO3HlwNEoW/VVzZE/+S",
	"0Ls09GM9h5z+HVNj53guheGiwjcGi92NTFl6mSlZ/qRy+2f7sG+ZyHTKSoQwDGZSwazK86FOFaKABSqJ",
	"+luYsTzXNAyMhFJqg+onlY/szqo8Z9Mck1OjKoycMqsU3dE5plJktK2Od0RVTFHZd44E4CV3iLnzoESV",
	"eizZmbuUmm/tJzbGnXDPbjeraVQc9Zvono98+QM3OR61mAkjd56skak9U3BhcG6PF8MvgmSYfBdGG4jG",
	"cPAFLnmKu9iXKrRs5ZlpASZjBoeGFxi70SMvPmfanCOKPVMfBGQH9Q2SMmfGTrlLMc9zjsJAGDC2r0LO",
	"pphDykpTKcyAGVA459o4rD+KRBQu5SU2UXkqZY5M2IeVRnVD3LKv/uCP2T7JC67LnK3BAgHkDMwCoVRy",
	"xnMEs+AaMrpT4BqmlhVbsu/ZQa9yRAN6IVcaVgupsR5pgOv+EcftZG/1UTcAGTRwqBvz3iucoUKROrRr",
	"IyGrMi7fMjGv2DwCCPcuXZwdCLkfCb035z9CKjPsj+A9Ks21wexbIKGDGUiRontlaJTlixpzTO2koBe8",
	"1Efdu66mRHEvhR2W7e7u5wWaBSoIAzUwhSAFTNeQ4YxVuRlt6KOBNOGFYw4exsbO/q3DjJytUQGrjBy6",
	"c2pgUDCTLqy0JABc/+a3T999wWcNgjrD3yrUEaHr8PCHTqpmWq+kahNS/ePgC7GBHo7mI5gkK5xOkgFM",
	"ErN0/y8XUuAk6X9LtCOAC6jJaZR00O6bCEp8OEypdr6DLNTOf5wCUo8cNOFV02oD7sfeoNN1u67wkPbm",
	"xY2VhfLSKcltEH2HTKECekoqTQNOEVhvHddvIsy+70wWKp34eBxwOxW7lyXXMsPzqiiYWkdgdQO1Ct2c",
	"P7gfNnurVYOjBXCBGWdW57yhZIooYVs0VilFROZQ/YEGhboqEMKbe/jN5sDmaLVqZZmZY8EdY2vuGhNg",
	"bchG75Nsjp1rxPDzfjRxw2LzvmIpRrCvtkzaYHUbtBJ/xvNCwzfg9E9ImVJry8x5kx01EMP9siugeLqA",
	"jBcotJV9lqctWV4hTDGXYq49O0JRFfYccxSKaIvNG6fZXAO9exgc9DSMHvjDxqDzlk9VlHxua2Fc13bz",
	"U0X3KOe8W6xdW27djrHv2WAX12YbM3gf2w7WsqV+R9TuIgwW+tC7P2lU791LG1xMmFJsvXOqsJ3GMrFD",
	"vQsc7AUaxvOv03ZOpTCMC1RH8bCbiAQLoPfMLKJITtTavqVde7R1F7c33eUS1ZLj6qgTX89Ot9AR893L",
	"fDmbWdV9SYrVkmeowA0dwMm//vH/H54cJWsU2m2f1ZgYs+UMm18TnPdi7tdIsHMKv+W9BPTe2xdbDDYc",
	"8SgCrycL+k4EFDkvuIlrLXI209jxzEjD8tijbcDQPsP4sFw9914QdGppXwMTubUz7Ssisq+UgDqJ5D0X",
	"827JqS2rcwYPfmJFmbudz6Vex25IG2Yq3R4tL2Mjl6g0dx7xzdAMlweNn7CjerHNXNHj5Wx9bpjBL2Of",
	"HOOarcrsgFPxOrr+Ad1+1w8a3u2ChiXRN2ImOxxRz2WG6VF01BL9u6KeK0yNXTAuaAo0CxnxHjxfICtR",
	"k/NibdeHkpkF/Osf/7SGwBKB6SHXA1BYsvSSfEGpLNfkDEp1fwBSgcIhCvtDU7F3GyIBUlSfLJ4pJrQd",
	"FdXzFTIfsTkICMsrjobbti2/AVMNkyZo993iOepAQzEvxZvjuGqEDDZIK6tpjsewPQdvFeGq7kFw4cqV",
	"wAxq0IN2ZxgAnwET6+PERadV3+mGP96/34WXhDXw/zZbpy2T38afwZ5NA9s93OiG/obda9gBuzZMXTOA",
	"oQM3bJ/PuwUt1XExnyT7PX4HAB8x4xqeOPqnv8RYJMftsHm4xkVGCULJuUKtfyLOe1+c/gAnjm30TDpJ",
	"H3gSywourATjuGoR+wbm5ykT3kdwhrrKXWA5y2gtlr9vHHTGco2DI903A/dEx1XS3K345lZh4kGiUyZE",
	"S4516SybBWt3RHi53mkMohY857XW0T76jAuuF9ejDrcPfg3Lf/eCIjqeqoTwSmckFHJdIt6CXZi8ufso",
	"rJCpdOE2GQFXIZfXOfcxBpFz3R0PShreOd/Wsf1+61U6jqyl6DR+vFP0+B1u+bxv7l3QtLF9fu5jPcMx",
	"5b81+2BzzDiILPS+Zh/TkSC9Q7+Mg+d1ELmJdjGb7yuxEoN5GA64x1B0ePIlXCkHyPxr9KO0t/xHppI/",
	"fSXdVLAH9zssLe/KP9bUuo5dpryuuI+SSJ+8hWK+2f4gqqTTHqIA8ZkRHxRLL2MGKGV+xNWdmVRpl/uZ",
	"x/IJKHtlwUSWow+WI/yM0//88AFQZKXkwtRpDVhMMcswO33sshqkPn346PGTp5OkP4obiFOM0OzrqmBi",
	"qJBl5IJwqRNh7TodpeTpJaqOebvSWr57/n745H9tUlnIUqy3LyaJ82FMkkpkkwRWCxRQiUshVyK6kstJ",
	"bVoVAQaWpZUo6tSciH0RVR7chI0zBDDVdzeobziGHB+CAfycpQu02nlE25xW2RzNd2uDbVuXC/OXJ9H4",
	"bs6X+IJ3WSze1u4eQNz++PW247mbtwetvbdXbuzyAGRKNuU5r2Ooba6yZNwzsS53ipURKDINlSYMpcg2",
	"17CQ2kCP5Su21sBFmlcZapgkWs7Miin0dHA8x3XZVNiR5+PdPpAupEZK+rIEkkox43NKNizrzDeQKosS",
	"yzZPqg/fWHwvMIP5H7EAy2MdKbIyH3iB73QXyDOwtljOxSbBA7iAguc5187kb2U1deOxLjEGTrcM0FNg",
	"lL5W5YaXOaU/KmS53QD0Ho2ewt/+Bo9GTz/1Wyt2HW4LvpuThq0MCE57QdwpABt+v7iDIfqEx+M413Ds",
	"dbnpQj5iyzGXypIySMhFDD1y5fVbjmINvdpt1296jY9zFpc5W+dcm6j+d4Y5I1Xpp7O3wQ36+u05UIYS",
	"hFc3aWANr+HuQg1U36cY7NJG8DNsexnuxLUYoEdzONfExklht5sjefhmjOeEgNrIsmzR+T4JVfsOA/Y1",
	"XOct5yG5DptuxOZFNaC5H/ft+53ZLwtcpvvQECF1yZgpE3TZ8Prlfz6H3uvRo7887VsWMnv3/sn43flL",
	"inFkaIjjwZIzIBfLOYnjEdcf1iWeV2Up7WlG8LNVDEjHBSbcpL48hWsgtMWMYiMcsz4wA8JhoUIt88rz",
	"LysfuJjDk/8ALrRBllkMnaL9rSYOyq22+30CD0/+elLaBbMm7cgZTKqTk8dIj/02NBim5mhoayN44RQG",
	"beciR6UDwROQIl/3RxMRzxLeoGwbwOeIl+AMNgtDz4Gh5/USODmaN+5cfDOV5wsXzlxHq9+TqNWplv/s",
	"Yn9dfvDjw4rdQURSCdJKcbM+t/v12hwltD6rXJrOVh43qqFPAXYJr1zrCjOrLLg6BFQv6sxXggHtjGbc",
	"wHZhTOkKorgPXm4jRD4bWu0HM89ZtVHICovJFDhUI/hA7LXE1JIIafJczHMMdGN5s6rMYiKCpv/6w4f3",
	"VpsxiqXGZZp/L/10YEW6mrEUiRzsM6JQ2lMgeqtxiTkKVFS+NlOyAG6gd1GwS4Tw4KLvSOr5G7AcUVtt",
	"LlN8ZjxZOKM3eUZxd3j2/k0j6H2anIwejk5IhylRsJInp8nj0cnoMSXNmQXdz5iVfLx8OGaVWYzdZdDv",
	"c+dLsUhCERIrfZO3XJsXfsygXfj36OTkWjVuR/mDGunSbX/vTvXbj/9hRz05edg1Zb3Zcassj7A2OG/o",
	"fD7ZWoc099Rn83qLuFFK0g+OAaubWgT/6L0oMUk/ZI1yRQ0rbhb1lI06PbrtKbcci4HAFdT0YTczEV6d",
	"9umBA1BoKmXFJzCYNnPHK22xSipgeW7tUm3FFAmbPNcOe9p3e9aiuMRRPWrznczWX6x6sbsm4qrNaKz4",
	"utpBsYd3uhGf6hLBLje6ZkquvPSGyOZZZHL6y8cm6gXwAwtXTpdX10tYvCD2uBngkvx3cPBqECXq8efg",
	"vrly+Ema1g6Jn1H5Uo0EJVOsQIPWdv7lc8IFZfBSup2TZC2nUOv6Bo2rOOR8+rhz1U8ihV/hFlyB1c2u",
	"wL70+PBLmzpmeuPJ4TfqauM2S3Hw3Lo06E0ShYYrdIy/ZimTJM5UrNDdBcj3VmurZ2YwUxxFlq+dV2oE",
	"z7KCCw0Fs/KUyuWYWNdFN469eR70LTBwsebmcKuB2VFcgVyJONewA38XdLk77tSsjTmKL5184S3Ea8zt",
	"tv44aO/wbQvbCMkPs6xczrlzKXhpuqWG0OO7wYFWRcM9X367WOFQy4NvvfDXTTp2csJoqAsIvrikam7C",
	"GpjNlclf0Vr+4F07cyiqbn6PxtdSBS/THQI/LHFnyuWZNa+X2FIqex54g41G5wimvxEMh8X8FFnqjurB",
	"uG0AWatkeG4XfLm0G/YWkLVrypytfyXXCKQLJuao62gGazXYqDSqAZRyhZYJQ6qk1sF6c/Vt4wUTmZzN",
	"RvCspesuOYP/Q6f4G/SYcHtwzgtImRDSgDXW7ZLPPPDoAmGBLEPVH8FLli6gQK3ZnJwYF2inOK39rRde",
	"n4b/e/7jD5Axw6Bk61yyDHoaEbbyIoc5v0SYccwz3bfGX+2K6TX21ndFwwpTKQSmRn9rra/6T2ut0R+p",
	"xXMouLYat0vxdWdmME59iwuQCsbBqQQzNOkiJk2/o4s8p8vZlaadxnNL8e9tgfeBg66DpatyJ7H8W4Vq",
	"vZHLAcs2xHJYR9smPoOfzJiuZugQrE192xPusjcB5+cvgWbwKPolCM/OuUH4JvlZnH6gIadwdc7WQ0cI",
	"6Iik566jqZH5ZLQ2+YVL3ms2h2Yn92I3tzqr3Jv1HFYdrkJ1/RikGGaYXgJtu+YsabtC9hCAZyxFozv5",
	"m6XfQmozJJvXFX45aWTVYD22cwMjhtUUlQ+0LyS1Q12m2AAUE5fOA2V3DE6y/esf/3T2tJGgK+fZybhO",
	"5RLVGlLqmQDfb9Z1CyqEAtUcM+DCSJACaXZKhUDL0Bp1q9rq12CvabTDFCz2vHIQOMAS3rFP4GBld+q0",
	"gy56D6ktG8yqQ/N/HSQF+8SLqkhOn54MkoIL98fDSDD0433gsysUvjdEfie1gVQWhRQBnj2PVt/Q5fbj",
	"6FQwwWdWbzyAz3Tm8WcXrLjap/7UqZRH2VZ19ONLGuJfTsPaLlv9kvd3O2uFduYoPqO9OX0C61ymAg2z",
	"asX1bnZcer1j3xW3Km/+DW65dZ6v54pfUDnNkOJsacixWEOGKadIcBBN3BHbtW65EXrtvOUw5t/khl3l",
	"3NdzvXXPjY0W19vqutE/fMeDpKxMzCdaSvX7XOGXd3BslcTcs4tjL+64LWWNS/xdcOk1MmWmyLziV2pU",
	"zjrdQqibqrNb7GNjKsWtd3qsa8S1egaJKwoLkJyarg0OlTXeQbs0ADJ7rarZd8Y4cD0R1A5rO+RqDVX7",
	"wNuQzkyEH8+AwQWNuADSHIFwfjARmlP7MAGvP7x7+xQuKL6fUqWjC/VfAOZY+MSGYNy3DPuY6euOeZ+q",
	"zuBgOLrHcoPKZ0e4CFwbTndqTTeJTKYG40Z1fcopF0xFaq93yexVleceh8JyV4Pk0clfIhF6pgxneRgH",
	"PYdlni/175M8O7yRTbnejO47yqAwfYsyrkucdYpsF31a80xvMn+poZx2uTRLazIulKzmC9+lkEt7BkgX",
	"jItTCOm4YPCTmQj/aq/2/NXFvn0o80rDjyWK87qdXspExp23iVKBN7mVo4kgjxlN+EDDBc8ugHu/k8sh",
	"9FnS9VKaT3Nrioa06RiJ2pPWy/9RFJnj6k5aSet3aWfeTjI9CxmwO/hGwWJxE+21xvDxZ5qrbZFuN16U",
	"WZWihh4TGWRcXw5Tli5Q952nmvLxa+yqRQ+0Jc9E3Ej0QFvyTIQXPbTqbUTP91ij9e8me1wpA882FEmh",
	"lK0qhotNEcPFAC5CCcPFRg61d+ovdO9W/2hikZzMS2Ou6Vv2DC9g+32R7yB5evIootQF8k1llWfUNnxK",
	"FVOWvDJ/2/iJwJw7vg0uJba/Pza3xRg2xHhNrrDJam5EYbcVU6aomarLehtqnmGjxYHLBN0EKEPKNUky",
	"bjS8fns+EXWS809nb0dwhiVSE2JSLzb+Ys0Kp/zCNyG18+/ShZQnAj9xbVwyn1uhka+qS7by2VEuERRm",
	"s6LEuV3Kbe3pyWMSn049Dgl8GpiLY9bnGYbZyXEKvSlLL4elNaQqhf24RsuUqXOF/+BWYzzn+cpbjy2C",
	"fXQHi3bHZv0j8LncIBWhxq0SJa5N4Y/v4WsHJoKLKStZatnAVsDLwgJ6HhR9Eplvz3fbj3RoDY2Khj0c",
	"opEyHM/SOEfjs47/4Ljfzp3+02Gy6z5n6jLgEXi8gDFUIvz7ho6SVsuNzsjq23rUfZgKoSvr/eYkt+NM",
	"eePExwFw/Lluo3I13rTz6ITpu9BB4zDdNvuz3EohvmaUkiKTIUz56ORQnLJjAV/ZH12hOeXJ8VNq52WI",
	"TFiXk4cqqPA380W5VKpe19Z/PMJueMWtLm61cBdhr2PKVDBGAfCxYXOvUTLBC+zWztk8uZZlsL04F5Rg",
	"6pIsNIZQfE+RWmftVldB96nMSbN0SBLbSui1HCHOw3WpZk1FEdQAf3fT79yVNoJ7DtzQc/0JOsHjhv3q",
	"+jJtNlbj4MM4vmwKimKGVaVR1SyTOHjX8qtalm7WDni0eVbzXJrl10gdW/d1vmQq56it/p0j0wgWHaFH",
	"tWCaL7sRx4771RquMfRp0ct2/wtz4+WM3L/YvQSyqefJnXH+75RcaQTHrom4IHD5G/H9Tc+lTr7vupn8",
	"yffvie/fht9vN7+/X4bvV/+T438Bjg89Np8rnJMqL5eoILTl6v8pDL56YdDofnXXkqBBdMdKgtI3aYpy",
	"/Pe+AP/ObNdmB+kO4OxxZp67hs7AqTjSrMmlGKpbN+fWa22w2Dp2+7NaXVk5u9/guvPSnuZid4Yv3/t0",
	"+pTlFNVz7vsHGkJCGpStM+8WnFVxh04cYHdVibUDq/uuw7qXy3JOnNvcVwPxFYaPR0YDeM+gEnzGMYNJ",
	"InCVr4EpxZeYTRKYUXsZl9eKlNnsOcqpFVMiY7kUGEmZFriyjHvGlTYjeOZ/f+BmZjl1xwlBwEISi7d7",
	"tEoDN7qWdQ+ArOAhM/SGNqwo9QC0tL+TC1+EsZSIQ2nYIbRAfLGXYVaVLk2bhQr+lKmsbwW+a7rBBAXW",
	"KNTN0kWY0ZeY+Pyai0suXMR84nqJThLXeMstNEm6ouNnDvpx9fl4FffRk0FTyfgqUrAPN3W9u7opC9R8",
	"PST88K6GXvsbULGE7EOiUadsT43hB8Xnc1TndlA8xLFNWXY+0CvEElZMw28VVreKQvzvA4twDSxXyLI1",
	"+BY6FknDsi0Q+sOQj7agLBmDgbpB4ZBmpZrkacVz17LinU9mb5ckd0JyvPnCQ5e0bXRkvkt9bLPK3VW6",
	"OD/2OGfaNK+k/vDEfnBRt+VOHn3mSlCoC6jBTwbceGcZuFSNAVUhDLy55VqEhCa3lmem0rPBplCJ+I9H",
	"4Hs+U7XKXElin9M1WAYYaGypR4HKXK2cS8rw+VSaqlbYAllG6ZKUumDB4nIF5Mzx2ZVUGQkB901U18bM",
	"CjX+aQTvUZY5jlP7mt2IkAbWGA5urcjdqhjXsvpQRYwbRflV0HPLDQtve5WhZK7TtvjtdokT79gnklQW",
	"vnYxgu8t63EePb1jYXCgeXGjTfidUderbcw/qnbrMNU5h1j44vXeuptr+MHqL2h/ren6rTbeX08um9tW",
	"q97G95qmS607kx+8Vgpld+dnPvPdiIMmHV4YuJpBVWsXblxQY13rDI1OMV8tZB7rlaER9XaXDFKBtf+k",
	"JDOdH/8gAS6ENMQQCQCkD/vGmd+A61wHvbrK2I+yPPg15kW/Sw3dKne+n8Do9rdn7jFAGrte6K0W8oGG",
	"uhZ1tWBmAKsFKhyAkKuDWk19YWPKcdzHLtp9be9Su4l10L0zyNaLAUEAKqq/733Hcivh+4dTRpogbLe1",
	"PQKSjRfuB6CNBe8MpL5Lr4a6mW27QW9oGBf624IUeB04R9jhLn/Yzqu6Hwaxm811rxxih//ulqPXLd5q",
	"Dnsd0H/28x5osHVuZHm9rMB63mupo0e11Dr33VV/FwXAyDIqFy0NlJWaoyuMr0xZmRtexPjzjOd4tb81",
	"isthpVceUFoqMGX4jKVGnzqvFaPObHWuau+Ciww/jYrH1V8v+oOJKFENl0xx5isQc6oJ6V24UpRffwgj",
	"qaMrcMGtajsvLJwmws7GjR1UPgn9Hn0lix/TmOnXH+x/o+KJvvDWmD2gRZSJIIdALldDuzxmzbzcETS3",
	"XOfluuRX9zn+Gv40kTY8zyF06YWekJvjrxQ3BoU10fod+fQ1gr/i+V0i+SA6l88tuw2t7ON/S5GN7N84",
	"KkqcV66z8549us8Ajovyya1Ltyxy1vcgVcCQe8917crB7UYaiyzbdZYNSvPdDgML6DmSG28T1YCIZ9A4",
	"+j4WvUCWm8V/7dM3XtOQ5LiqgzJnfEvy7f+aaSxd2ce0NLjdrTuh+gwyLFFkKNK1D+dbKs2YYVOmsW/n",
	"qMSmKf6+UJqVgAK1vVWWcfsvKJWcYjSM1p6n3cL3l4+WWBxncbRM+J+ME/u7n+tzTdRuTkum/heKWFx9",
	"vPrvAAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
