//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for PlaybackInfoMethod.
const (
	PlaybackInfoMethodDirect    PlaybackInfoMethod = "direct"
	PlaybackInfoMethodRemux     PlaybackInfoMethod = "remux"
	PlaybackInfoMethodTranscode PlaybackInfoMethod = "transcode"
)

// Valid indicates whether the value is a known member of the PlaybackInfoMethod enum.
func (e PlaybackInfoMethod) Valid() bool {
	switch e {
	case PlaybackInfoMethodDirect:
		return true
	case PlaybackInfoMethodRemux:
		return true
	case PlaybackInfoMethodTranscode:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	Admin  Role = "admin"
	Viewer Role = "viewer"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case Admin:
		return true
	case Viewer:
		return true
	default:
		return false
	}
}

// Defines values for SubtitleTrackSource.
const (
	Embedded      SubtitleTrackSource = "embedded"
	Opensubtitles SubtitleTrackSource = "opensubtitles"
)

// Valid indicates whether the value is a known member of the SubtitleTrackSource enum.
func (e SubtitleTrackSource) Valid() bool {
	switch e {
	case Embedded:
		return true
	case Opensubtitles:
		return true
	default:
		return false
	}
}

// Defines values for TranscodeSessionMethod.
const (
	TranscodeSessionMethodRemux     TranscodeSessionMethod = "remux"
	TranscodeSessionMethodTranscode TranscodeSessionMethod = "transcode"
)

// Valid indicates whether the value is a known member of the TranscodeSessionMethod enum.
func (e TranscodeSessionMethod) Valid() bool {
	switch e {
	case TranscodeSessionMethodRemux:
		return true
	case TranscodeSessionMethodTranscode:
		return true
	default:
		return false
	}
}

// Defines values for TranscodeSessionState.
const (
	Complete TranscodeSessionState = "complete"
	Failed   TranscodeSessionState = "failed"
	Running  TranscodeSessionState = "running"
	Starting TranscodeSessionState = "starting"
	Stopped  TranscodeSessionState = "stopped"
)

// Valid indicates whether the value is a known member of the TranscodeSessionState enum.
func (e TranscodeSessionState) Valid() bool {
	switch e {
	case Complete:
		return true
	case Failed:
		return true
	case Running:
		return true
	case Starting:
		return true
	case Stopped:
		return true
	default:
		return false
	}
}

// Defines values for ListMoviesParamsSort.
const (
	ListMoviesParamsSortAdded ListMoviesParamsSort = "added"
	ListMoviesParamsSortTitle ListMoviesParamsSort = "title"
	ListMoviesParamsSortYear  ListMoviesParamsSort = "year"
)

// Valid indicates whether the value is a known member of the ListMoviesParamsSort enum.
func (e ListMoviesParamsSort) Valid() bool {
	switch e {
	case ListMoviesParamsSortAdded:
		return true
	case ListMoviesParamsSortTitle:
		return true
	case ListMoviesParamsSortYear:
		return true
	default:
		return false
	}
}

// Defines values for ListSeriesParamsSort.
const (
	ListSeriesParamsSortTitle ListSeriesParamsSort = "title"
	ListSeriesParamsSortYear  ListSeriesParamsSort = "year"
)

// Valid indicates whether the value is a known member of the ListSeriesParamsSort enum.
func (e ListSeriesParamsSort) Valid() bool {
	switch e {
	case ListSeriesParamsSortTitle:
		return true
	case ListSeriesParamsSortYear:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// ContinueItem defines model for ContinueItem.
type ContinueItem struct {
	DurationSeconds *float32            `json:"durationSeconds,omitempty"`
	Id              openapi_types.UUID  `json:"id"`
	Kind            string              `json:"kind"`
	Percent         float32             `json:"percent"`
	PositionSeconds float32             `json:"positionSeconds"`
	PosterUrl       *string             `json:"posterUrl,omitempty"`
	SeriesId        *openapi_types.UUID `json:"seriesId,omitempty"`
	SeriesTitle     *string             `json:"seriesTitle,omitempty"`
	Title           string              `json:"title"`
	Year            *int                `json:"year,omitempty"`
}

// Device defines model for Device.
type Device struct {
	CreatedAt  time.Time          `json:"createdAt"`
	Id         openapi_types.UUID `json:"id"`
	LastSeenAt *time.Time         `json:"lastSeenAt,omitempty"`
	Name       string             `json:"name"`

	// Platform Client platform/type label captured at registration.
	Platform *string             `json:"platform,omitempty"`
	Revoked  bool                `json:"revoked"`
	UserId   *openapi_types.UUID `json:"userId"`

	// UserName Display name of the profile this device is bound to (the Fleet shows whose device it is).
	UserName *string `json:"userName,omitempty"`
}

// DeviceRegistrationRequest defines model for DeviceRegistrationRequest.
type DeviceRegistrationRequest struct {
	DeviceName string `json:"deviceName"`
	Password   string `json:"password"`

	// Platform Client platform/type label (e.g. "web", "tv", "phone"); shown in the Fleet.
	Platform *string `json:"platform,omitempty"`

	// UserId The profile this device is bound to.
	UserId   openapi_types.UUID `json:"userId"`
	Username string             `json:"username"`
}

// DeviceRegistrationResponse defines model for DeviceRegistrationResponse.
type DeviceRegistrationResponse struct {
	Device Device `json:"device"`

	// Token Bearer token for this device.
	Token string `json:"token"`
}

// DeviceRenameRequest defines model for DeviceRenameRequest.
type DeviceRenameRequest struct {
	Name string `json:"name"`
}

// EpisodeSummary defines model for EpisodeSummary.
type EpisodeSummary struct {
	DurationSeconds *float32            `json:"durationSeconds,omitempty"`
	EpisodeNumber   int                 `json:"episodeNumber"`
	Id              openapi_types.UUID  `json:"id"`
	MediaItemId     *openapi_types.UUID `json:"mediaItemId,omitempty"`

	// PositionSeconds Current profile's resume position.
	PositionSeconds *float32 `json:"positionSeconds,omitempty"`
	Title           *string  `json:"title,omitempty"`
	Watched         *bool    `json:"watched,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Library defines model for Library.
type Library struct {
	Id   openapi_types.UUID `json:"id"`
	Kind string             `json:"kind"`
	Name string             `json:"name"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Account  Account       `json:"account"`
	Profiles []UserProfile `json:"profiles"`
}

// MediaItemDetail defines model for MediaItemDetail.
type MediaItemDetail struct {
	Container       *string            `json:"container,omitempty"`
	DurationSeconds *float32           `json:"durationSeconds,omitempty"`
	FilePath        string             `json:"filePath"`
	Genres          *[]string          `json:"genres,omitempty"`
	Id              openapi_types.UUID `json:"id"`
	Kind            string             `json:"kind"`
	Overview        *string            `json:"overview,omitempty"`
	PosterUrl       *string            `json:"posterUrl,omitempty"`
	ReviewRequired  bool               `json:"reviewRequired"`
	Tags            []string           `json:"tags"`
	Title           string             `json:"title"`
	Year            *int               `json:"year,omitempty"`
}

// MediaItemPage defines model for MediaItemPage.
type MediaItemPage struct {
	Items  []MediaItemSummary `json:"items"`
	Limit  int                `json:"limit"`
	Offset int                `json:"offset"`
	Total  int                `json:"total"`
}

// MediaItemSummary defines model for MediaItemSummary.
type MediaItemSummary struct {
	Id        openapi_types.UUID `json:"id"`
	Kind      string             `json:"kind"`
	PosterUrl *string            `json:"posterUrl,omitempty"`
	Tags      []string           `json:"tags"`
	Title     string             `json:"title"`
	Year      *int               `json:"year,omitempty"`
}

// PingResponse defines model for PingResponse.
type PingResponse struct {
	Service string `json:"service"`
	Status  string `json:"status"`
	Version string `json:"version"`
}

// PlayState defines model for PlayState.
type PlayState struct {
	DurationSeconds *float32   `json:"durationSeconds,omitempty"`
	PositionSeconds float32    `json:"positionSeconds"`
	UpdatedAt       *time.Time `json:"updatedAt,omitempty"`
	Watched         bool       `json:"watched"`
}

// PlaybackInfo defines model for PlaybackInfo.
type PlaybackInfo struct {
	AudioCodec *string `json:"audioCodec,omitempty"`
	Container  string  `json:"container"`
	DirectPlay bool    `json:"directPlay"`

	// Method Cheapest playable path — serve as-is, repackage (copy codecs), or re-encode.
	Method     PlaybackInfoMethod `json:"method"`
	Reason     *string            `json:"reason,omitempty"`
	VideoCodec *string            `json:"videoCodec,omitempty"`
}

// PlaybackInfoMethod Cheapest playable path — serve as-is, repackage (copy codecs), or re-encode.
type PlaybackInfoMethod string

// PlaybackSession defines model for PlaybackSession.
type PlaybackSession struct {
	DeviceId        openapi_types.UUID `json:"deviceId"`
	DurationSeconds *float64           `json:"durationSeconds,omitempty"`

	// Encoder Encoder of the owned transcode session, if any.
	Encoder  *string            `json:"encoder,omitempty"`
	ItemId   openapi_types.UUID `json:"itemId"`
	LastSeen time.Time          `json:"lastSeen"`

	// Method remux | transcode, if this session owns a transcode session.
	Method          *string   `json:"method,omitempty"`
	PositionSeconds float64   `json:"positionSeconds"`
	StartedAt       time.Time `json:"startedAt"`

	// State e.g. "playing"
	State  string             `json:"state"`
	UserId openapi_types.UUID `json:"userId"`
}

// ProgressUpdate defines model for ProgressUpdate.
type ProgressUpdate struct {
	DurationSeconds *float32 `json:"durationSeconds,omitempty"`
	PositionSeconds float32  `json:"positionSeconds"`
}

// Role defines model for Role.
type Role string

// ScanLibraryResult defines model for ScanLibraryResult.
type ScanLibraryResult struct {
	Error     *string            `json:"error,omitempty"`
	Errors    int                `json:"errors"`
	LibraryId openapi_types.UUID `json:"libraryId"`
	Name      string             `json:"name"`
	Scanned   int                `json:"scanned"`
}

// ScanStatus defines model for ScanStatus.
type ScanStatus struct {
	FinishedAt *time.Time          `json:"finishedAt,omitempty"`
	Libraries  []ScanLibraryResult `json:"libraries"`
	Running    bool                `json:"running"`
	StartedAt  *time.Time          `json:"startedAt,omitempty"`
}

// SeasonSummary defines model for SeasonSummary.
type SeasonSummary struct {
	Episodes     []EpisodeSummary   `json:"episodes"`
	Id           openapi_types.UUID `json:"id"`
	SeasonNumber int                `json:"seasonNumber"`
	Title        *string            `json:"title,omitempty"`
}

// SeriesDetail defines model for SeriesDetail.
type SeriesDetail struct {
	Id        openapi_types.UUID `json:"id"`
	Overview  *string            `json:"overview,omitempty"`
	PosterUrl *string            `json:"posterUrl,omitempty"`
	Seasons   []SeasonSummary    `json:"seasons"`
	Tags      []string           `json:"tags"`
	Title     string             `json:"title"`
	Year      *int               `json:"year,omitempty"`
}

// SeriesPage defines model for SeriesPage.
type SeriesPage struct {
	Items  []SeriesSummary `json:"items"`
	Limit  int             `json:"limit"`
	Offset int             `json:"offset"`
	Total  int             `json:"total"`
}

// SeriesSummary defines model for SeriesSummary.
type SeriesSummary struct {
	Id        openapi_types.UUID `json:"id"`
	PosterUrl *string            `json:"posterUrl,omitempty"`
	Tags      []string           `json:"tags"`
	Title     string             `json:"title"`
	Year      *int               `json:"year,omitempty"`
}

// Session defines model for Session.
type Session struct {
	AccountId openapi_types.UUID `json:"accountId"`
	DeviceId  openapi_types.UUID `json:"deviceId"`
	Role      Role               `json:"role"`
	UserId    openapi_types.UUID `json:"userId"`
}

// SubtitleTrack defines model for SubtitleTrack.
type SubtitleTrack struct {
	Default bool `json:"default"`
	Forced  bool `json:"forced"`

	// Id Track handle for the WebVTT endpoint (e.g. "embedded:3", "os:12345").
	Id string `json:"id"`

	// Label Human-readable label for the subtitle picker.
	Label string `json:"label"`

	// Language BCP-47 language code (e.g. "en"), or "und" when unknown.
	Language string              `json:"language"`
	Source   SubtitleTrackSource `json:"source"`
}

// SubtitleTrackSource defines model for SubtitleTrack.Source.
type SubtitleTrackSource string

// TranscodeCacheStats defines model for TranscodeCacheStats.
type TranscodeCacheStats struct {
	BudgetBytes int64 `json:"budgetBytes"`
	LiveDirs    int   `json:"liveDirs"`
	SessionDirs int   `json:"sessionDirs"`
	TotalBytes  int64 `json:"totalBytes"`
}

// TranscodeCapabilities defines model for TranscodeCapabilities.
type TranscodeCapabilities struct {
	// Available Encoder backends usable on this host (always includes "software").
	Available []string `json:"available"`

	// Selected The encoder chosen by the configured preference order.
	Selected string `json:"selected"`
}

// TranscodeProgress defines model for TranscodeProgress.
type TranscodeProgress struct {
	Fps float64 `json:"fps"`

	// OutTimeMs Encoded timeline position in milliseconds.
	OutTimeMs int64 `json:"outTimeMs"`

	// Speed Encode speed as a multiple of realtime (2.5 == 2.5x).
	Speed float64 `json:"speed"`
}

// TranscodeSession defines model for TranscodeSession.
type TranscodeSession struct {
	Encoder string             `json:"encoder"`
	Error   *string            `json:"error,omitempty"`
	Id      string             `json:"id"`
	ItemId  openapi_types.UUID `json:"itemId"`

	// Method Whether this session copies codecs (remux) or re-encodes (transcode).
	Method TranscodeSessionMethod `json:"method"`

	// PlaylistUrl Relative URL of the HLS media playlist for this session.
	PlaylistUrl string                `json:"playlistUrl"`
	Progress    TranscodeProgress     `json:"progress"`
	StartAt     float64               `json:"startAt"`
	StartedAt   time.Time             `json:"startedAt"`
	State       TranscodeSessionState `json:"state"`
}

// TranscodeSessionMethod Whether this session copies codecs (remux) or re-encodes (transcode).
type TranscodeSessionMethod string

// TranscodeSessionState defines model for TranscodeSession.State.
type TranscodeSessionState string

// TranscodeStartRequest defines model for TranscodeStartRequest.
type TranscodeStartRequest struct {
	// Hevc Whether the client can play HEVC (H.265) in fMP4/MSE — detected via MediaSource.isTypeSupported. When true, an HEVC source is remuxed (copied) at native resolution including 4K instead of being re-encoded to H.264 1080p, and re-encodes of >1080p sources target HEVC. Defaults to false (H.264 only).
	Hevc *bool `json:"hevc,omitempty"`

	// StartAt Seek offset in seconds (default 0).
	StartAt *float64 `json:"startAt,omitempty"`
}

// UserProfile defines model for UserProfile.
type UserProfile struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
	Role Role               `json:"role"`
}

// WatchedUpdate defines model for WatchedUpdate.
type WatchedUpdate struct {
	Watched bool `json:"watched"`
}

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// StreamItemParams defines parameters for StreamItem.
type StreamItemParams struct {
	// Token Per-device token (alternative to the bearer header).
	Token *string `form:"token,omitempty" json:"token,omitempty"`
}

// GetSubtitleParams defines parameters for GetSubtitle.
type GetSubtitleParams struct {
	// Token Per-device token (alternative to the bearer header).
	Token *string `form:"token,omitempty" json:"token,omitempty"`
}

// ListMoviesParams defines parameters for ListMovies.
type ListMoviesParams struct {
	Limit  *int                  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int                  `form:"offset,omitempty" json:"offset,omitempty"`
	Sort   *ListMoviesParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Tag Filter to items carrying this tag (e.g. anime).
	Tag *string `form:"tag,omitempty" json:"tag,omitempty"`
}

// ListMoviesParamsSort defines parameters for ListMovies.
type ListMoviesParamsSort string

// ListSeriesParams defines parameters for ListSeries.
type ListSeriesParams struct {
	Limit  *int                  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int                  `form:"offset,omitempty" json:"offset,omitempty"`
	Sort   *ListSeriesParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Tag Filter to series carrying this tag (e.g. anime).
	Tag *string `form:"tag,omitempty" json:"tag,omitempty"`
}

// ListSeriesParamsSort defines parameters for ListSeries.
type ListSeriesParamsSort string

// ListRecentParams defines parameters for ListRecent.
type ListRecentParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// RegisterDeviceJSONRequestBody defines body for RegisterDevice for application/json ContentType.
type RegisterDeviceJSONRequestBody = DeviceRegistrationRequest

// RenameDeviceJSONRequestBody defines body for RenameDevice for application/json ContentType.
type RenameDeviceJSONRequestBody = DeviceRenameRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ReportProgressJSONRequestBody defines body for ReportProgress for application/json ContentType.
type ReportProgressJSONRequestBody = ProgressUpdate

// StartTranscodeJSONRequestBody defines body for StartTranscode for application/json ContentType.
type StartTranscodeJSONRequestBody = TranscodeStartRequest

// SetWatchedJSONRequestBody defines body for SetWatched for application/json ContentType.
type SetWatchedJSONRequestBody = WatchedUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List devices in the current account (the Fleet)
	// (GET /api/v1/auth/devices)
	ListDevices(w http.ResponseWriter, r *http.Request)
	// Register a device for a profile and issue a device token
	// (POST /api/v1/auth/devices)
	RegisterDevice(w http.ResponseWriter, r *http.Request)
	// Revoke a device token ("retire from the Fleet")
	// (DELETE /api/v1/auth/devices/{deviceId})
	RevokeDevice(w http.ResponseWriter, r *http.Request, deviceId openapi_types.UUID)
	// Rename a device in the Fleet
	// (PATCH /api/v1/auth/devices/{deviceId})
	RenameDevice(w http.ResponseWriter, r *http.Request, deviceId openapi_types.UUID)
	// Authenticate an account and list its profiles
	// (POST /api/v1/auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Resolve the current (account, profile, device) from the token
	// (GET /api/v1/auth/me)
	GetCurrentSession(w http.ResponseWriter, r *http.Request)
	// Continue-watching / on-deck items for the current profile
	// (GET /api/v1/continue)
	ListContinue(w http.ResponseWriter, r *http.Request)
	// Media item detail with effective metadata
	// (GET /api/v1/items/{itemId})
	GetMediaItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// Direct-play capability decision for the item
	// (GET /api/v1/items/{itemId}/playback)
	GetPlaybackInfo(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// Current play-state (resume position) for the item
	// (GET /api/v1/items/{itemId}/progress)
	GetProgress(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// Heartbeat — upsert the resume position for the current profile
	// (PUT /api/v1/items/{itemId}/progress)
	ReportProgress(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// Direct-play media stream with HTTP range support
	// (GET /api/v1/items/{itemId}/stream)
	StreamItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID, params StreamItemParams)
	// Available subtitle tracks for an item
	// (GET /api/v1/items/{itemId}/subtitles)
	ListSubtitles(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// A subtitle track as WebVTT
	// (GET /api/v1/items/{itemId}/subtitles/{trackId})
	GetSubtitle(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID, trackId string, params GetSubtitleParams)
	// Start (or join) an HLS transcode session for an item
	// (POST /api/v1/items/{itemId}/transcode)
	StartTranscode(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// Mark an item watched / unwatched for the current profile
	// (POST /api/v1/items/{itemId}/watched)
	SetWatched(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// List the account's libraries
	// (GET /api/v1/libraries)
	ListLibraries(w http.ResponseWriter, r *http.Request)
	// Browse movies in a library
	// (GET /api/v1/libraries/{libraryId}/movies)
	ListMovies(w http.ResponseWriter, r *http.Request, libraryId openapi_types.UUID, params ListMoviesParams)
	// Browse series in a library
	// (GET /api/v1/libraries/{libraryId}/series)
	ListSeries(w http.ResponseWriter, r *http.Request, libraryId openapi_types.UUID, params ListSeriesParams)
	// Service identity and version
	// (GET /api/v1/ping)
	Ping(w http.ResponseWriter, r *http.Request)
	// Recently-added items (films + series) across the account
	// (GET /api/v1/recent)
	ListRecent(w http.ResponseWriter, r *http.Request, params ListRecentParams)
	// Trigger an immediate library re-scan ("rebuild the Manifest")
	// (POST /api/v1/scan)
	TriggerScan(w http.ResponseWriter, r *http.Request)
	// Current/last scan sweep status
	// (GET /api/v1/scan/status)
	GetScanStatus(w http.ResponseWriter, r *http.Request)
	// Series detail with seasons and episodes
	// (GET /api/v1/series/{seriesId})
	GetSeries(w http.ResponseWriter, r *http.Request, seriesId openapi_types.UUID)
	// Live playback sessions (who's watching what, where, now)
	// (GET /api/v1/sessions)
	ListPlaybackSessions(w http.ResponseWriter, r *http.Request)
	// Transcode cache usage (Ballast)
	// (GET /api/v1/transcode/cache)
	GetTranscodeCache(w http.ResponseWriter, r *http.Request)
	// Encoders available on this host and the selected one
	// (GET /api/v1/transcode/capabilities)
	GetTranscodeCapabilities(w http.ResponseWriter, r *http.Request)
	// Live transcode sessions for the current account (The Helm)
	// (GET /api/v1/transcode/sessions)
	ListTranscodeSessions(w http.ResponseWriter, r *http.Request)
	// Stop a transcode session and purge its output
	// (DELETE /api/v1/transcode/{sessionId})
	StopTranscode(w http.ResponseWriter, r *http.Request, sessionId string)
	// HLS artifact for a session (master/variant playlist, init, or segment)
	// (GET /api/v1/transcode/{sessionId}/{file})
	GetTranscodeFile(w http.ResponseWriter, r *http.Request, sessionId string, file string)
	// Liveness/readiness probe
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListDevices operation middleware
func (siw *ServerInterfaceWrapper) ListDevices(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDevices(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterDevice operation middleware
func (siw *ServerInterfaceWrapper) RegisterDevice(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterDevice(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeDevice operation middleware
func (siw *ServerInterfaceWrapper) RevokeDevice(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "deviceId" -------------
	var deviceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "deviceId", r.PathValue("deviceId"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "deviceId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeDevice(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RenameDevice operation middleware
func (siw *ServerInterfaceWrapper) RenameDevice(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "deviceId" -------------
	var deviceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "deviceId", r.PathValue("deviceId"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "deviceId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RenameDevice(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentSession operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentSession(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListContinue operation middleware
func (siw *ServerInterfaceWrapper) ListContinue(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListContinue(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMediaItem operation middleware
func (siw *ServerInterfaceWrapper) GetMediaItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMediaItem(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPlaybackInfo operation middleware
func (siw *ServerInterfaceWrapper) GetPlaybackInfo(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlaybackInfo(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProgress operation middleware
func (siw *ServerInterfaceWrapper) GetProgress(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProgress(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReportProgress operation middleware
func (siw *ServerInterfaceWrapper) ReportProgress(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReportProgress(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamItem operation middleware
func (siw *ServerInterfaceWrapper) StreamItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params StreamItemParams

	// ------------- Optional query parameter "token" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "token", r.URL.Query(), &params.Token, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "token"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamItem(w, r, itemId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSubtitles operation middleware
func (siw *ServerInterfaceWrapper) ListSubtitles(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSubtitles(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSubtitle operation middleware
func (siw *ServerInterfaceWrapper) GetSubtitle(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	// ------------- Path parameter "trackId" -------------
	var trackId string

	err = runtime.BindStyledParameterWithOptions("simple", "trackId", r.PathValue("trackId"), &trackId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "trackId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSubtitleParams

	// ------------- Optional query parameter "token" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "token", r.URL.Query(), &params.Token, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "token"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSubtitle(w, r, itemId, trackId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartTranscode operation middleware
func (siw *ServerInterfaceWrapper) StartTranscode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartTranscode(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetWatched operation middleware
func (siw *ServerInterfaceWrapper) SetWatched(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetWatched(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListLibraries operation middleware
func (siw *ServerInterfaceWrapper) ListLibraries(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLibraries(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMovies operation middleware
func (siw *ServerInterfaceWrapper) ListMovies(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "libraryId" -------------
	var libraryId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "libraryId", r.PathValue("libraryId"), &libraryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "libraryId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMoviesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tag", r.URL.Query(), &params.Tag, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tag"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMovies(w, r, libraryId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSeries operation middleware
func (siw *ServerInterfaceWrapper) ListSeries(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "libraryId" -------------
	var libraryId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "libraryId", r.PathValue("libraryId"), &libraryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "libraryId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSeriesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tag", r.URL.Query(), &params.Tag, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tag"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSeries(w, r, libraryId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Ping operation middleware
func (siw *ServerInterfaceWrapper) Ping(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Ping(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRecent operation middleware
func (siw *ServerInterfaceWrapper) ListRecent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRecentParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRecent(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerScan operation middleware
func (siw *ServerInterfaceWrapper) TriggerScan(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerScan(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetScanStatus operation middleware
func (siw *ServerInterfaceWrapper) GetScanStatus(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetScanStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSeries operation middleware
func (siw *ServerInterfaceWrapper) GetSeries(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "seriesId" -------------
	var seriesId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "seriesId", r.PathValue("seriesId"), &seriesId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "seriesId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSeries(w, r, seriesId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPlaybackSessions operation middleware
func (siw *ServerInterfaceWrapper) ListPlaybackSessions(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPlaybackSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTranscodeCache operation middleware
func (siw *ServerInterfaceWrapper) GetTranscodeCache(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTranscodeCache(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTranscodeCapabilities operation middleware
func (siw *ServerInterfaceWrapper) GetTranscodeCapabilities(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTranscodeCapabilities(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTranscodeSessions operation middleware
func (siw *ServerInterfaceWrapper) ListTranscodeSessions(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTranscodeSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopTranscode operation middleware
func (siw *ServerInterfaceWrapper) StopTranscode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId string

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopTranscode(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTranscodeFile operation middleware
func (siw *ServerInterfaceWrapper) GetTranscodeFile(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId string

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	// ------------- Path parameter "file" -------------
	var file string

	err = runtime.BindStyledParameterWithOptions("simple", "file", r.PathValue("file"), &file, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "file", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTranscodeFile(w, r, sessionId, file)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/auth/devices", wrapper.ListDevices)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/auth/devices", wrapper.RegisterDevice)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/auth/devices/{deviceId}", wrapper.RevokeDevice)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/auth/devices/{deviceId}", wrapper.RenameDevice)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/auth/login", wrapper.Login)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/auth/me", wrapper.GetCurrentSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/continue", wrapper.ListContinue)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/items/{itemId}", wrapper.GetMediaItem)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/items/{itemId}/playback", wrapper.GetPlaybackInfo)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/items/{itemId}/progress", wrapper.GetProgress)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/api/v1/items/{itemId}/progress", wrapper.ReportProgress)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/items/{itemId}/stream", wrapper.StreamItem)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/items/{itemId}/subtitles", wrapper.ListSubtitles)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/items/{itemId}/subtitles/{trackId}", wrapper.GetSubtitle)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/items/{itemId}/transcode", wrapper.StartTranscode)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/items/{itemId}/watched", wrapper.SetWatched)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/libraries", wrapper.ListLibraries)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/libraries/{libraryId}/movies", wrapper.ListMovies)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/libraries/{libraryId}/series", wrapper.ListSeries)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/ping", wrapper.Ping)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/recent", wrapper.ListRecent)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/scan", wrapper.TriggerScan)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/scan/status", wrapper.GetScanStatus)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/series/{seriesId}", wrapper.GetSeries)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/sessions", wrapper.ListPlaybackSessions)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/transcode/cache", wrapper.GetTranscodeCache)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/transcode/capabilities", wrapper.GetTranscodeCapabilities)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/transcode/sessions", wrapper.ListTranscodeSessions)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/transcode/{sessionId}", wrapper.StopTranscode)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/transcode/{sessionId}/{file}", wrapper.GetTranscodeFile)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealth)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H3rcts4lvCrnOL3VUWq0cVJnNlZd80Pdy6d1CRpl+1M/2ilxhB5JKFNAmwAlKLJumofYp9wn2QLBwBF",
	"SqQuvnUyNfkTmwSBg3O/Af4axTLLpUBhdHTyNVKocyk00i9vpBrzJEFhf4mlMCiM/ZHlecpjZrgUw9+0",
	"pNc6nmHG7E//X+EkOon+33A189C91cPXSkkV3dzc9KIEdax4bieJTqLTwsxQGDsrJjAuDAhpgKWpXGAS",
	"3fSij9K8kYVIHh6Uc9SyUDESBBNa86YXfRKsMDOp+D/xEWD4wLXmYgpSARdzlvIEYoWJxRBLdWQ/8HPY",
	"JU7jWBYOllzJHJXhjoCcQJ1IlTETnURFwZOoF5lljtFJpI3iYmr3JliGduDai5tepPD3giu7418j+paG",
	"fi7nkOPfMDZ2jpdSGC4KfGcw2wQkKRTh5wJjKRJ6JIo0ZeMUoxOjCixnFEU2RmVn3BP4a+6YYuNFjir2",
	"FNqYO5ear8HTNMag+qTSLdCuVtOoOOp3jTDv+fElNynutZgJIzfeLJGpLVNwYXBqt9dEW8JkmHwTRyuM",
	"NtH/Fc55jJuUjxVakT41NcQkzGDf8AybKLon4VOmzQWi2DL1TkS2cH4vylNm7JTEvDXRfJlyFAbCgKH9",
	"FFI2xhRilptCYQLMgMIp18Zx/WAfUBTO5TVWWXksZYpM2JeFRnVL3rKffvTbrO/kFdd5ypZgkQByAmaG",
	"kCs54SmCmXENCdEUuIaxVYNgJHTsoDcpogE9kwsNi5nUWI40wHV3j+22qpZyqyuE9Co81M555xV8n+Pv",
	"BeoGfejA/NhKdKb1Qqo6nsuHvXvikg4OpgMYRQscj6IejCIzd//nMylwFHV/INQK4AJKbA+iFtI6rqgv",
	"frmbkHa+nRJm59/PNpQje1V8laSs4H1fCjo3pI2Euwyr10ZWVcpr57/UUfQjMoUK6C1MpKriqQHXa9v1",
	"QITZt+3JYqWVH/dDbqvNfZ1zLRO8KLKMqeX9WF10c350D1awlZZjb/2cYcKZdQduqbgabPSajBVKkZA5",
	"Vn+iQaEuMoTw5RZFtNqw2dvqLpiJZ05Dt4wtNXaTfqtjtpGe5A5ukBHD4+1s4oY1zfuej1Ujg9zVxTrU",
	"cfRTNcIop7xdcR+sme+murYA2KaX2MoH36aYgqtu+duxrSOEwUzv+vaTRnXmPiLGdRAypdhyY1cBnMoy",
	"TZv6EGT0FRrG0wb3TQrDuEC1l4TcRuFY4M6YmTUy2BSFWsPQpjNcw8Pd4wY5RzXnuNhrx4cFCQrtxOcl",
	"nZpcPcOmB274UaKBkkwbu/Agb2WvMzZtkJlyi3uxfzlZsHcNqEh5xk2z1ZKTicaWd0Yalja9WkcMwRnG",
	"h+XKubeioNVK3znOPYgFv1H2amWhMy6m7VpXW1F17iB+YVmeOsinUi+bcKgNM4Wuj5bXTSPnqDR3qZzV",
	"0ATnO13DAFG52Gquxu2lbHlhmMH78d72yWsUebIjIj/EE9rh+WwmEcK3bdgYs/j6nZjIBhNbJFy+lAnG",
	"e3F6zXRtmiquMDZ2wWY1nKGZyYbY6uUMWY6aQrulXR9yZmbwv//9P2BJj8B0n+seKMxZfM2mCJ1Y5kuI",
	"Ldy62wOpQGEfhX1gHVQURUYxBQFE6jUrvlg+U0xoO6qCqqopYT7VuBMRc57g3nhbj3RWaCpxUkXtNipe",
	"oA4y1BTDvdtP7zWIwYppZTFOcR8v3+FbbdLztXsR8h9yITCBEvWg3R56wCfAxHKvTA5vjXlac1j7J8fa",
	"+JK4Bv5rBTqBTFGt34Pdmwa2ubnBLaOxTTJsoF0bpg7M/umgDev780kTK3VcTEfR9nzIDsQ3hACVPAX9",
	"6InYlAZ1EFY3VyFko0AoOVWo9SfSvI+l6Xdo4iZAz6Wz9EEnsSTjwlowjouasK9wfhEz4ePLc9RF6ioi",
	"SUJrsfSsstEJSzX29gxue+6NbnbYUrfiuzvVN3qRjpkQNTvW5rOsFixD2fBxCWkTRi16Lkqvo771CRdc",
	"zw6TDgcHPyBq3CRQg4+nCiHsCo2m8GAhXsNdmLwKfSOuyKS1+sk+f7L/ztfSY7cPFTUBti0ltm8SqckT",
	"rs3eW22zGUUWe23B+p7becAA1+3lAOaskbwp+PhGwpUQp4QNbolYHI3uI+J1M31X4W4d5Nty6PcZ0u6M",
	"ZVsdYp+t29cjPsR9Vt6kb+MzMvt38J9W4PcafSmCoREhxZiQdqlYfN0UJ0yY9yg2rdJEqrgth8abimJ2",
	"DZgxkaToKz4Iv+D475eXgCLJJRemrM1hNsYkweTkuSvNSX3y9Nnz4xejqDto9uPHmG6u+bbImOgrZAlF",
	"iq7+F9bWfvOQ8/gaVcu8Ylp4TbJWwHp51j/+DwgDKL5cgS9GkQs1R1EhklEEixkKKMS1kAvRuJLreak6",
	"fwEHVuBzFAFc3eAGNpo1N2FlDwFNJe16JYWbmOMyxCkvWTxD60Q1+FDjIpmi+XFpsB6ScGH+fBz1Gl3H",
	"Ob7ibY6lD4naB5Au3H+9NcxUvu7VYK+vXIFyB2ZyNuYpL8skda0yZ9wrsbao14bpKBINhSYOlcKFjDOp",
	"DXRYumBLDVzEaZGghlGk5cQsmEIvB/trXI0pxgZbitU+Ood4JjUKGC9JQGIpJnxKDRW5wgkqFDGCVEmj",
	"sKzrpHLzlcW3IjNEaQ2Oer5vvCsLc8kz/KDbUJ6AdZlTLlZVSuACMp6mXLvIrFaab+djnWMTOt0yQG+B",
	"2Xg/K1LD85RaPBSy1AIAnWeDF/DXv8KzwYsv3dqKbZtbw+9qpwGUHuFpK4pbDWAlPdMcBza+4c0J8QPy",
	"L23ZlF9maGao6vmTWOYctc/kQYcyLt1aPk9Dp8yudKvJvf1yennKlinXxjs+622JKTN8jvDp/H3IVr19",
	"fwFUZofw6aqXoZLc2VyowurbHINN2Qjh4How+CAZoIA9msNFkKtY0oKbIiViJoynxIDayDyvyfk2C1Wm",
	"eAL3VTKctRwPZXiq2Z4qoSrY3M779vvWAvcM5/E2NkSIXUdRzAQRG96+/vtL6LwdPPvzi65VIZMPZ8fD",
	"DxevKRWdoCGNB3POgEpQF2SOB1xfLnO8KPJc2t0M4BfrGJCPC0y4SX37K9dAbIsJpbA5Jl1gBoTjQoVa",
	"poXXX9Y+cDGF478BF9ogSyyHjtE+K4WD+scsvMfw9OgvR7ldMKnKjpzAqDg6eo702oOhwTA1RUOgDeCV",
	"cxi0nYvySQ4FxyBFuuwORiLqtWUwHAvWEXyBeA0unLE49BoYOt4vgaO9deMG4avV+ntuzD3Eq9/Si9Hq",
	"lv/iSjRt6cr9qz/ttR5yCeJCcbO8sPB6b466sk4L1w1QJ9UZqr7vY3NdW1zrAhPrLLheS1SvyvYtwgFB",
	"RjOucDszJncN19zXmNYZIp30rfeDides2ihkmeVkqu+oAVySes0xtiJCnjwX0xSD3FjdrAozG4ng6b+9",
	"vDyz3oxRLDY/0KOfpJ8OrElXExYjiYN9RxJKMAWhtx6XmKJARe3xEyUz4AY6Vxm7RggvrrpOpF6+A6sR",
	"tfXmEsUnxouFC3qjUyqPwunZu0pt8iQ6GjwdHJEPk6NgOY9OoueDo8Fz6osxM6LPkOV8OH86ZIWZDR0x",
	"6PnUZRosk1Ai21rf6D3X5pUf06sfLHh2dHRQD/1e2ZJKz1+9M2aju/7nv9lRx0dP26YsgR3W2v6Ja0Nq",
	"g/bnOwZ16NWMfUuaj4gr7bLdkBiwvqll8M8+z9Fk6fuschxCw4KbWTll5RwAUXvMrcZiIHABpXxYYEbC",
	"u9O+A6gHCk2hrPkEBuNqA2ShLVdJBSxNbVyqrZkiY5Om2nFPnbbnNYmLnNSjNj/KZHlvpyPaG3tv6orG",
	"mq+bDRZ7+qCA+I6EBu5yo0ul5I6v3JLZvIqMTn79XGW9gH5ggeREvLLp1/IFqcfVANepusGDN71GoR5+",
	"DembG8ef5GltiPg5tWiXTJAzxTI0aGPnX79GXFCTHvUMOUtWSwrVyNerkGJX8unzBqmPG5rbAxVcE/nt",
	"SGA/er77o9U5KfriePcX5Wmmukpx+FwjGnRGkULDFTrFX6qUUdSsVKzR3UTIT9ZrK2dmMFEcRZIuXVZq",
	"AKdJxoWGjFl7SkcCmFiWneNOvXkd9AMwcCXB6nDrgdlRXIFciGatYQf+IezycNqp2uC9l146umcQms+w",
	"WbC+H7Z3/LbGbcTku1VWKqfcpRS8NV1zQ+j1w/BArWn5kYlf70fedaTyB2/8dVWOnZ0wGsoe4Xu3VFUg",
	"bIBZXZnyFbXld9LahUON7uZPaPyBgJBlekDkhyUezLk8t+H1HGtOZccjr7fy6JzAdFeGYbeZj/1Bza1+",
	"ezjN+SiOe+3o6KO572HVPgWp1ikeghT9BONrILDLQk1cP2dSwa7vCqkjmD4efnXZpZtt/Fr2Bu9lDMt0",
	"1X16TvcnEutHCe6TcHczLwQZ0RQSgs0FVDiZYEy5rAwNS5hhh1F2mPs+x20krnW0/gtQubafb4fEr6hN",
	"tU+J0TgUxaz3GnNK3QdR5k7YDqJyJVfeSuUw5l+Ewq4j/dshb3nSL2XLPqXmobN21q+7m8a9KC9MUxCb",
	"S/XHkPD+PdK1VtNH9km38o4DKakQ8Q/hpbfIlBkjM1QoKXKNyhDfrDHU/Zj/oUsfV5THWr6ZXuuScZ9o",
	"n3amPA7ZqfHSYF8xMUXQrm4DHY14zcW0OwDrYAPXI0Gn99dz5HPOaGqf7ZshS1DBz+fA4IpGXMHvBaol",
	"EM/3RkJzQZloeHv54f0LuKKCTEwnCFxt5gowxcxXooQ0oNEQEJY67raDhsjfbfMxXZ3ezvpBh6UGlS9n",
	"uZRpHU+uxcF+SzhagRec7BU0d1PQMjZo+itOadjlmAumGs40bYrZmyJNPQ+F5W560bOjPzeUVJgynKVh",
	"HHQcl3m91H1M8WwJH6t2vVqOcZJBdZWaZBwqnGVPU5t82mBIr1q1jGLxtXbFzzkmYGZKFtOZvzqDS7sH",
	"iGeMixMI/VNg8IsZCf9ppwzVykM0XcjTQsPPOYrQEKetdCU8cen/GYpKM8xgJF6zeOZgeaLhiidXwDVM",
	"kIptwHRoayuX0nyc2ggn9Lk1iajdabn89+LI7NdGW+syfMgA826W6TS0LG3wG2X3xW2815LDh19prnpE",
	"uqYOlEyKGDV0mEgg4fq6H7N4hrrrUgvUQFlyV2l6oG55RuJWpgfqlmckvOmhVe9ien7Ckq3/MNvjek95",
	"spJIyn2ttZ1erbpOr3pwFXpOr1Z2qA6pJ+hWUL83s2h15XBuTF3Mdxo9r/ACtz+W+PaiF0fPGpy6IL6x",
	"LNKE7pEb0408VrwST238QmhOnd4G18PU3Z5MXVMMK2E8UCus2tAqafN1x5Qpo4H5NoW+5glWjg661p1V",
	"Rjn0yJEl40bD2/cXI1F2pX06fz+Ac8yRbsYi92KVX9Msc84v/Cn04vwmXQ1gJPAL18Z1X7gVKg1GOmcL",
	"X852nTswmWQ5Tu1SDrQXR8/JfDr3OHRcaGAu8Vzupx9mpyMO0Bmz+Lqf20CqUNht9miZMmVz13ceNTY3",
	"qd346LEmsM8eYNH2ZLp/Bb75DqQi1rhTZetgCX/+CNdfmgZejFnOYqsG6m4C0Qg6HhVdMpnvLzaP9bZ4",
	"DZUW1C0aotLj1VxWu0Dj28S+c96vN7v9O2GymT5n6jrwEXi+gCEUIvx8y0RJ7ShrayXqfTnqMUKFcFPW",
	"4zaRVUqyTzSklR3vh8Dh1/J48s0wk/NdOP3ghuwjt9Vzz3dyiJscxnCecDVReeLrxVEvytgXnhVZdPLs",
	"yP7GhfvtadMpm+YF/EHFxhWqUx7tP6V2WYaGCcvzf6FtPfzO/CkqOlv4eY9w4Q23Lrh1vl0hMmZKLa2f",
	"Q439hk29C8kEz7DdHWfTe8xR3bIYSMdgH0x6flRyoREcywMXwCBIyq1kx93Du1V23AHXf8vOI8nOLWTG",
	"EfE7FJrKwfGHlhiPo0MkJvf3QzRKxpk/nfNgflL1FrAW5GwJnC/cpVzAqXPaLCl8Da3vq33rpba+cm3b",
	"CsMl4o05s1MoBJ9wTGAUCVykS2BK8TkmowgmdAQvVlJrwDmqZUD1iY1nRMJSKRAmPM1cJ7cjSg8ELlAb",
	"mHClzQBO/fMnbmaW0gnCkHfLpLYRtYXRRsQ2qA0XSDwBMjx9ZugLbViW6x5oaZ9T1CzCWKp90SGEEM0T",
	"e3QSTIrcHdxh4ZRDzFTSBcX8wSQmKJdF2WUWz8KMA6ActS9pXV1z4ZLUo4iU9Shyh5PdQqOoLSF97rDf",
	"rG3314jPjisa8elOjfgoWend1xk+XG+ZRWq67BN/eB+j4/jwT5723cC4Fd90l4bQMdvSh3mp+HSK6sIO",
	"as4qrEuWnQ/0AjGHBdPwe4HFnQL//9yxCNfAUoUsWYI/ZmiZNCxbQ6HfDIVFGRWmDAbpBoV9mpX6tscF",
	"T92xng9M8AnqtbbtVkwOV5cVtrWdVC4XekiztFrl4ZrxXOg4TJk2VZKUdyhuRxc6Ty78DYatTXcHOHDl",
	"33T4Vnt1atcBfTuFLAdWrdnO35tDdq684WgnWSmP1V6cPXXte6EPLyS+dI/MYl+Ves6NCwbVHXTQ6Lpr",
	"FzOZNp1s0Ih6/UwDGWOXXDMzZlpv1CNVIoQ0lL8hBJBl9tcc/AncOWPoKIyliHkaRl3OEN5imnXbDOLa",
	"3YqPkxVZv9DxEbMjTeSFzmImn2goG3cXM2Z6sJihwh4IudipX0uCDanAuU1d1G8heUg923TfyYNhtlwM",
	"CANQaLqq9EeWWhXc3Z0vrqKwfgnJHpisfPA4CK0s+GAo9XeqaCivHqlfpxKO94bbSEAKPATPDepwUz+s",
	"F1UeR0FslnIeVUNs6N/N3v3yQG6pYQ9B/Vc/747jkBdG5oeVBMt5Dyri73UA8sLfhfGHOABG5o120cpA",
	"Xqgpkj2UhckLc0tCDL9OeIrt3Sw25kdXwKZPnlBNGpgyfMJio09c/MzoHG1ZqO5ccZHgl0H2vPjLVbc3",
	"Ejmq/pwpznz7cUoNYZ0r14f2j49hJN2/AVxwAxqnmcXTSNjZuLGD8uNwOt+3sfkxlZn+8dH+G2TH+qo7",
	"IE/AbtAyykhQaJLKRd8uj0m1KD+AKshlUd5Vvt1fACrxTxNpw9MUwp0q0BFytf2F4saggCWabkszTcng",
	"b3j6kEzea5zLF5buIivb9N9cJAP7Ow6yHKeFu4dnC4zubu1hlh/fuW/TMmdJB6kChzx6obutAN/ONJZZ",
	"1pusK5Lmz6YHFdBxIjdcF6oeCU+vsvVtKnqGLDWzf27zN97SkGi/lqM8ZXzN8m3/EwFNvQoq/JUtB92y",
	"FaunkGCOIkERL31a2kppwgwbM41dO0chVleYbcttWgsoUFuqsoTbnyBXcoyNec36PPULV379bIXFaRYn",
	"y8T/0TCyz/1cX0uhdnNaMfVP6Kjhzeeb/wsAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
