//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for PlaybackInfoMethod.
const (
	PlaybackInfoMethodDirect    PlaybackInfoMethod = "direct"
	PlaybackInfoMethodRemux     PlaybackInfoMethod = "remux"
	PlaybackInfoMethodTranscode PlaybackInfoMethod = "transcode"
)

// Valid indicates whether the value is a known member of the PlaybackInfoMethod enum.
func (e PlaybackInfoMethod) Valid() bool {
	switch e {
	case PlaybackInfoMethodDirect:
		return true
	case PlaybackInfoMethodRemux:
		return true
	case PlaybackInfoMethodTranscode:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	Admin  Role = "admin"
	Viewer Role = "viewer"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case Admin:
		return true
	case Viewer:
		return true
	default:
		return false
	}
}

// Defines values for SubtitleTrackSource.
const (
	Embedded      SubtitleTrackSource = "embedded"
	Opensubtitles SubtitleTrackSource = "opensubtitles"
)

// Valid indicates whether the value is a known member of the SubtitleTrackSource enum.
func (e SubtitleTrackSource) Valid() bool {
	switch e {
	case Embedded:
		return true
	case Opensubtitles:
		return true
	default:
		return false
	}
}

// Defines values for TranscodeSessionMethod.
const (
	TranscodeSessionMethodRemux     TranscodeSessionMethod = "remux"
	TranscodeSessionMethodTranscode TranscodeSessionMethod = "transcode"
)

// Valid indicates whether the value is a known member of the TranscodeSessionMethod enum.
func (e TranscodeSessionMethod) Valid() bool {
	switch e {
	case TranscodeSessionMethodRemux:
		return true
	case TranscodeSessionMethodTranscode:
		return true
	default:
		return false
	}
}

// Defines values for TranscodeSessionState.
const (
	Complete TranscodeSessionState = "complete"
	Failed   TranscodeSessionState = "failed"
	Running  TranscodeSessionState = "running"
	Starting TranscodeSessionState = "starting"
	Stopped  TranscodeSessionState = "stopped"
)

// Valid indicates whether the value is a known member of the TranscodeSessionState enum.
func (e TranscodeSessionState) Valid() bool {
	switch e {
	case Complete:
		return true
	case Failed:
		return true
	case Running:
		return true
	case Starting:
		return true
	case Stopped:
		return true
	default:
		return false
	}
}

// Defines values for ListMoviesParamsSort.
const (
	ListMoviesParamsSortAdded ListMoviesParamsSort = "added"
	ListMoviesParamsSortTitle ListMoviesParamsSort = "title"
	ListMoviesParamsSortYear  ListMoviesParamsSort = "year"
)

// Valid indicates whether the value is a known member of the ListMoviesParamsSort enum.
func (e ListMoviesParamsSort) Valid() bool {
	switch e {
	case ListMoviesParamsSortAdded:
		return true
	case ListMoviesParamsSortTitle:
		return true
	case ListMoviesParamsSortYear:
		return true
	default:
		return false
	}
}

// Defines values for ListSeriesParamsSort.
const (
	ListSeriesParamsSortTitle ListSeriesParamsSort = "title"
	ListSeriesParamsSortYear  ListSeriesParamsSort = "year"
)

// Valid indicates whether the value is a known member of the ListSeriesParamsSort enum.
func (e ListSeriesParamsSort) Valid() bool {
	switch e {
	case ListSeriesParamsSortTitle:
		return true
	case ListSeriesParamsSortYear:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// ContinueItem defines model for ContinueItem.
type ContinueItem struct {
	DurationSeconds *float32            `json:"durationSeconds,omitempty"`
	Id              openapi_types.UUID  `json:"id"`
	Kind            string              `json:"kind"`
	Percent         float32             `json:"percent"`
	PositionSeconds float32             `json:"positionSeconds"`
	PosterUrl       *string             `json:"posterUrl,omitempty"`
	SeriesId        *openapi_types.UUID `json:"seriesId,omitempty"`
	SeriesTitle     *string             `json:"seriesTitle,omitempty"`
	Title           string              `json:"title"`
	Year            *int                `json:"year,omitempty"`
}

// Device defines model for Device.
type Device struct {
	CreatedAt  time.Time          `json:"createdAt"`
	Id         openapi_types.UUID `json:"id"`
	LastSeenAt *time.Time         `json:"lastSeenAt,omitempty"`
	Name       string             `json:"name"`

	// Platform Client platform/type label captured at registration.
	Platform *string             `json:"platform,omitempty"`
	Revoked  bool                `json:"revoked"`
	UserId   *openapi_types.UUID `json:"userId"`

	// UserName Display name of the profile this device is bound to (the Fleet shows whose device it is).
	UserName *string `json:"userName,omitempty"`
}

// DeviceRegistrationRequest defines model for DeviceRegistrationRequest.
type DeviceRegistrationRequest struct {
	DeviceName string `json:"deviceName"`
	Password   string `json:"password"`

	// Platform Client platform/type label (e.g. "web", "tv", "phone"); shown in the Fleet.
	Platform *string `json:"platform,omitempty"`

	// UserId The profile this device is bound to.
	UserId   openapi_types.UUID `json:"userId"`
	Username string             `json:"username"`
}

// DeviceRegistrationResponse defines model for DeviceRegistrationResponse.
type DeviceRegistrationResponse struct {
	Device Device `json:"device"`

	// Token Bearer token for this device.
	Token string `json:"token"`
}

// DeviceRenameRequest defines model for DeviceRenameRequest.
type DeviceRenameRequest struct {
	Name string `json:"name"`
}

// EpisodeSummary defines model for EpisodeSummary.
type EpisodeSummary struct {
	DurationSeconds *float32            `json:"durationSeconds,omitempty"`
	EpisodeNumber   int                 `json:"episodeNumber"`
	Id              openapi_types.UUID  `json:"id"`
	MediaItemId     *openapi_types.UUID `json:"mediaItemId,omitempty"`

	// PositionSeconds Current profile's resume position.
	PositionSeconds *float32 `json:"positionSeconds,omitempty"`
	Title           *string  `json:"title,omitempty"`
	Watched         *bool    `json:"watched,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Library defines model for Library.
type Library struct {
	Id   openapi_types.UUID `json:"id"`
	Kind string             `json:"kind"`
	Name string             `json:"name"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Account  Account       `json:"account"`
	Profiles []UserProfile `json:"profiles"`
}

// MediaItemDetail defines model for MediaItemDetail.
type MediaItemDetail struct {
	Container       *string            `json:"container,omitempty"`
	DurationSeconds *float32           `json:"durationSeconds,omitempty"`
	FilePath        string             `json:"filePath"`
	Genres          *[]string          `json:"genres,omitempty"`
	Id              openapi_types.UUID `json:"id"`
	Kind            string             `json:"kind"`
	Overview        *string            `json:"overview,omitempty"`
	PosterUrl       *string            `json:"posterUrl,omitempty"`
	ReviewRequired  bool               `json:"reviewRequired"`
	Tags            []string           `json:"tags"`
	Title           string             `json:"title"`
	Year            *int               `json:"year,omitempty"`
}

// MediaItemPage defines model for MediaItemPage.
type MediaItemPage struct {
	Items  []MediaItemSummary `json:"items"`
	Limit  int                `json:"limit"`
	Offset int                `json:"offset"`
	Total  int                `json:"total"`
}

// MediaItemSummary defines model for MediaItemSummary.
type MediaItemSummary struct {
	Id        openapi_types.UUID `json:"id"`
	Kind      string             `json:"kind"`
	PosterUrl *string            `json:"posterUrl,omitempty"`
	Tags      []string           `json:"tags"`
	Title     string             `json:"title"`
	Year      *int               `json:"year,omitempty"`
}

// PingResponse defines model for PingResponse.
type PingResponse struct {
	Service string `json:"service"`
	Status  string `json:"status"`
	Version string `json:"version"`
}

// PlayState defines model for PlayState.
type PlayState struct {
	DurationSeconds *float32   `json:"durationSeconds,omitempty"`
	PositionSeconds float32    `json:"positionSeconds"`
	UpdatedAt       *time.Time `json:"updatedAt,omitempty"`
	Watched         bool       `json:"watched"`
}

// PlaybackInfo defines model for PlaybackInfo.
type PlaybackInfo struct {
	AudioCodec *string `json:"audioCodec,omitempty"`
	Container  string  `json:"container"`
	DirectPlay bool    `json:"directPlay"`

	// Method Cheapest playable path — serve as-is, repackage (copy codecs), or re-encode.
	Method     PlaybackInfoMethod `json:"method"`
	Reason     *string            `json:"reason,omitempty"`
	VideoCodec *string            `json:"videoCodec,omitempty"`
}

// PlaybackInfoMethod Cheapest playable path — serve as-is, repackage (copy codecs), or re-encode.
type PlaybackInfoMethod string

// ProgressUpdate defines model for ProgressUpdate.
type ProgressUpdate struct {
	DurationSeconds *float32 `json:"durationSeconds,omitempty"`
	PositionSeconds float32  `json:"positionSeconds"`
}

// Role defines model for Role.
type Role string

// ScanLibraryResult defines model for ScanLibraryResult.
type ScanLibraryResult struct {
	Error     *string            `json:"error,omitempty"`
	Errors    int                `json:"errors"`
	LibraryId openapi_types.UUID `json:"libraryId"`
	Name      string             `json:"name"`
	Scanned   int                `json:"scanned"`
}

// ScanStatus defines model for ScanStatus.
type ScanStatus struct {
	FinishedAt *time.Time          `json:"finishedAt,omitempty"`
	Libraries  []ScanLibraryResult `json:"libraries"`
	Running    bool                `json:"running"`
	StartedAt  *time.Time          `json:"startedAt,omitempty"`
}

// SeasonSummary defines model for SeasonSummary.
type SeasonSummary struct {
	Episodes     []EpisodeSummary   `json:"episodes"`
	Id           openapi_types.UUID `json:"id"`
	SeasonNumber int                `json:"seasonNumber"`
	Title        *string            `json:"title,omitempty"`
}

// SeriesDetail defines model for SeriesDetail.
type SeriesDetail struct {
	Id        openapi_types.UUID `json:"id"`
	Overview  *string            `json:"overview,omitempty"`
	PosterUrl *string            `json:"posterUrl,omitempty"`
	Seasons   []SeasonSummary    `json:"seasons"`
	Tags      []string           `json:"tags"`
	Title     string             `json:"title"`
	Year      *int               `json:"year,omitempty"`
}

// SeriesPage defines model for SeriesPage.
type SeriesPage struct {
	Items  []SeriesSummary `json:"items"`
	Limit  int             `json:"limit"`
	Offset int             `json:"offset"`
	Total  int             `json:"total"`
}

// SeriesSummary defines model for SeriesSummary.
type SeriesSummary struct {
	Id        openapi_types.UUID `json:"id"`
	PosterUrl *string            `json:"posterUrl,omitempty"`
	Tags      []string           `json:"tags"`
	Title     string             `json:"title"`
	Year      *int               `json:"year,omitempty"`
}

// Session defines model for Session.
type Session struct {
	AccountId openapi_types.UUID `json:"accountId"`
	DeviceId  openapi_types.UUID `json:"deviceId"`
	Role      Role               `json:"role"`
	UserId    openapi_types.UUID `json:"userId"`
}

// SubtitleTrack defines model for SubtitleTrack.
type SubtitleTrack struct {
	Default bool `json:"default"`
	Forced  bool `json:"forced"`

	// Id Track handle for the WebVTT endpoint (e.g. "embedded:3", "os:12345").
	Id string `json:"id"`

	// Label Human-readable label for the subtitle picker.
	Label string `json:"label"`

	// Language BCP-47 language code (e.g. "en"), or "und" when unknown.
	Language string              `json:"language"`
	Source   SubtitleTrackSource `json:"source"`
}

// SubtitleTrackSource defines model for SubtitleTrack.Source.
type SubtitleTrackSource string

// TranscodeCacheStats defines model for TranscodeCacheStats.
type TranscodeCacheStats struct {
	BudgetBytes int64 `json:"budgetBytes"`
	LiveDirs    int   `json:"liveDirs"`
	SessionDirs int   `json:"sessionDirs"`
	TotalBytes  int64 `json:"totalBytes"`
}

// TranscodeCapabilities defines model for TranscodeCapabilities.
type TranscodeCapabilities struct {
	// Available Encoder backends usable on this host (always includes "software").
	Available []string `json:"available"`

	// Selected The encoder chosen by the configured preference order.
	Selected string `json:"selected"`
}

// TranscodeProgress defines model for TranscodeProgress.
type TranscodeProgress struct {
	Fps float64 `json:"fps"`

	// OutTimeMs Encoded timeline position in milliseconds.
	OutTimeMs int64 `json:"outTimeMs"`

	// Speed Encode speed as a multiple of realtime (2.5 == 2.5x).
	Speed float64 `json:"speed"`
}

// TranscodeSession defines model for TranscodeSession.
type TranscodeSession struct {
	Encoder string             `json:"encoder"`
	Error   *string            `json:"error,omitempty"`
	Id      string             `json:"id"`
	ItemId  openapi_types.UUID `json:"itemId"`

	// Method Whether this session copies codecs (remux) or re-encodes (transcode).
	Method TranscodeSessionMethod `json:"method"`

	// PlaylistUrl Relative URL of the HLS media playlist for this session.
	PlaylistUrl string                `json:"playlistUrl"`
	Progress    TranscodeProgress     `json:"progress"`
	StartAt     float64               `json:"startAt"`
	StartedAt   time.Time             `json:"startedAt"`
	State       TranscodeSessionState `json:"state"`
}

// TranscodeSessionMethod Whether this session copies codecs (remux) or re-encodes (transcode).
type TranscodeSessionMethod string

// TranscodeSessionState defines model for TranscodeSession.State.
type TranscodeSessionState string

// TranscodeStartRequest defines model for TranscodeStartRequest.
type TranscodeStartRequest struct {
	// Hevc Whether the client can play HEVC (H.265) in fMP4/MSE — detected via MediaSource.isTypeSupported. When true, an HEVC source is remuxed (copied) at native resolution including 4K instead of being re-encoded to H.264 1080p, and re-encodes of >1080p sources target HEVC. Defaults to false (H.264 only).
	Hevc *bool `json:"hevc,omitempty"`

	// StartAt Seek offset in seconds (default 0).
	StartAt *float64 `json:"startAt,omitempty"`
}

// UserProfile defines model for UserProfile.
type UserProfile struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
	Role Role               `json:"role"`
}

// WatchedUpdate defines model for WatchedUpdate.
type WatchedUpdate struct {
	Watched bool `json:"watched"`
}

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// StreamItemParams defines parameters for StreamItem.
type StreamItemParams struct {
	// Token Per-device token (alternative to the bearer header).
	Token *string `form:"token,omitempty" json:"token,omitempty"`
}

// GetSubtitleParams defines parameters for GetSubtitle.
type GetSubtitleParams struct {
	// Token Per-device token (alternative to the bearer header).
	Token *string `form:"token,omitempty" json:"token,omitempty"`
}

// ListMoviesParams defines parameters for ListMovies.
type ListMoviesParams struct {
	Limit  *int                  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int                  `form:"offset,omitempty" json:"offset,omitempty"`
	Sort   *ListMoviesParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Tag Filter to items carrying this tag (e.g. anime).
	Tag *string `form:"tag,omitempty" json:"tag,omitempty"`
}

// ListMoviesParamsSort defines parameters for ListMovies.
type ListMoviesParamsSort string

// ListSeriesParams defines parameters for ListSeries.
type ListSeriesParams struct {
	Limit  *int                  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int                  `form:"offset,omitempty" json:"offset,omitempty"`
	Sort   *ListSeriesParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Tag Filter to series carrying this tag (e.g. anime).
	Tag *string `form:"tag,omitempty" json:"tag,omitempty"`
}

// ListSeriesParamsSort defines parameters for ListSeries.
type ListSeriesParamsSort string

// ListRecentParams defines parameters for ListRecent.
type ListRecentParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// RegisterDeviceJSONRequestBody defines body for RegisterDevice for application/json ContentType.
type RegisterDeviceJSONRequestBody = DeviceRegistrationRequest

// RenameDeviceJSONRequestBody defines body for RenameDevice for application/json ContentType.
type RenameDeviceJSONRequestBody = DeviceRenameRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ReportProgressJSONRequestBody defines body for ReportProgress for application/json ContentType.
type ReportProgressJSONRequestBody = ProgressUpdate

// StartTranscodeJSONRequestBody defines body for StartTranscode for application/json ContentType.
type StartTranscodeJSONRequestBody = TranscodeStartRequest

// SetWatchedJSONRequestBody defines body for SetWatched for application/json ContentType.
type SetWatchedJSONRequestBody = WatchedUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List devices in the current account (the Fleet)
	// (GET /api/v1/auth/devices)
	ListDevices(w http.ResponseWriter, r *http.Request)
	// Register a device for a profile and issue a device token
	// (POST /api/v1/auth/devices)
	RegisterDevice(w http.ResponseWriter, r *http.Request)
	// Revoke a device token ("retire from the Fleet")
	// (DELETE /api/v1/auth/devices/{deviceId})
	RevokeDevice(w http.ResponseWriter, r *http.Request, deviceId openapi_types.UUID)
	// Rename a device in the Fleet
	// (PATCH /api/v1/auth/devices/{deviceId})
	RenameDevice(w http.ResponseWriter, r *http.Request, deviceId openapi_types.UUID)
	// Authenticate an account and list its profiles
	// (POST /api/v1/auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Resolve the current (account, profile, device) from the token
	// (GET /api/v1/auth/me)
	GetCurrentSession(w http.ResponseWriter, r *http.Request)
	// Continue-watching / on-deck items for the current profile
	// (GET /api/v1/continue)
	ListContinue(w http.ResponseWriter, r *http.Request)
	// Media item detail with effective metadata
	// (GET /api/v1/items/{itemId})
	GetMediaItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// Direct-play capability decision for the item
	// (GET /api/v1/items/{itemId}/playback)
	GetPlaybackInfo(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// Current play-state (resume position) for the item
	// (GET /api/v1/items/{itemId}/progress)
	GetProgress(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// Heartbeat — upsert the resume position for the current profile
	// (PUT /api/v1/items/{itemId}/progress)
	ReportProgress(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// Direct-play media stream with HTTP range support
	// (GET /api/v1/items/{itemId}/stream)
	StreamItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID, params StreamItemParams)
	// Available subtitle tracks for an item
	// (GET /api/v1/items/{itemId}/subtitles)
	ListSubtitles(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// A subtitle track as WebVTT
	// (GET /api/v1/items/{itemId}/subtitles/{trackId})
	GetSubtitle(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID, trackId string, params GetSubtitleParams)
	// Start (or join) an HLS transcode session for an item
	// (POST /api/v1/items/{itemId}/transcode)
	StartTranscode(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// Mark an item watched / unwatched for the current profile
	// (POST /api/v1/items/{itemId}/watched)
	SetWatched(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// List the account's libraries
	// (GET /api/v1/libraries)
	ListLibraries(w http.ResponseWriter, r *http.Request)
	// Browse movies in a library
	// (GET /api/v1/libraries/{libraryId}/movies)
	ListMovies(w http.ResponseWriter, r *http.Request, libraryId openapi_types.UUID, params ListMoviesParams)
	// Browse series in a library
	// (GET /api/v1/libraries/{libraryId}/series)
	ListSeries(w http.ResponseWriter, r *http.Request, libraryId openapi_types.UUID, params ListSeriesParams)
	// Service identity and version
	// (GET /api/v1/ping)
	Ping(w http.ResponseWriter, r *http.Request)
	// Recently-added items (films + series) across the account
	// (GET /api/v1/recent)
	ListRecent(w http.ResponseWriter, r *http.Request, params ListRecentParams)
	// Trigger an immediate library re-scan ("rebuild the Manifest")
	// (POST /api/v1/scan)
	TriggerScan(w http.ResponseWriter, r *http.Request)
	// Current/last scan sweep status
	// (GET /api/v1/scan/status)
	GetScanStatus(w http.ResponseWriter, r *http.Request)
	// Series detail with seasons and episodes
	// (GET /api/v1/series/{seriesId})
	GetSeries(w http.ResponseWriter, r *http.Request, seriesId openapi_types.UUID)
	// Transcode cache usage (Ballast)
	// (GET /api/v1/transcode/cache)
	GetTranscodeCache(w http.ResponseWriter, r *http.Request)
	// Encoders available on this host and the selected one
	// (GET /api/v1/transcode/capabilities)
	GetTranscodeCapabilities(w http.ResponseWriter, r *http.Request)
	// Live transcode sessions for the current account (The Helm)
	// (GET /api/v1/transcode/sessions)
	ListTranscodeSessions(w http.ResponseWriter, r *http.Request)
	// Stop a transcode session and purge its output
	// (DELETE /api/v1/transcode/{sessionId})
	StopTranscode(w http.ResponseWriter, r *http.Request, sessionId string)
	// HLS artifact for a session (master/variant playlist, init, or segment)
	// (GET /api/v1/transcode/{sessionId}/{file})
	GetTranscodeFile(w http.ResponseWriter, r *http.Request, sessionId string, file string)
	// Liveness/readiness probe
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListDevices operation middleware
func (siw *ServerInterfaceWrapper) ListDevices(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDevices(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterDevice operation middleware
func (siw *ServerInterfaceWrapper) RegisterDevice(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterDevice(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeDevice operation middleware
func (siw *ServerInterfaceWrapper) RevokeDevice(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "deviceId" -------------
	var deviceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "deviceId", r.PathValue("deviceId"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "deviceId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeDevice(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RenameDevice operation middleware
func (siw *ServerInterfaceWrapper) RenameDevice(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "deviceId" -------------
	var deviceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "deviceId", r.PathValue("deviceId"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "deviceId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RenameDevice(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentSession operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentSession(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListContinue operation middleware
func (siw *ServerInterfaceWrapper) ListContinue(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListContinue(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMediaItem operation middleware
func (siw *ServerInterfaceWrapper) GetMediaItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMediaItem(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPlaybackInfo operation middleware
func (siw *ServerInterfaceWrapper) GetPlaybackInfo(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlaybackInfo(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProgress operation middleware
func (siw *ServerInterfaceWrapper) GetProgress(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProgress(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReportProgress operation middleware
func (siw *ServerInterfaceWrapper) ReportProgress(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReportProgress(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamItem operation middleware
func (siw *ServerInterfaceWrapper) StreamItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params StreamItemParams

	// ------------- Optional query parameter "token" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "token", r.URL.Query(), &params.Token, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "token"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamItem(w, r, itemId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSubtitles operation middleware
func (siw *ServerInterfaceWrapper) ListSubtitles(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSubtitles(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSubtitle operation middleware
func (siw *ServerInterfaceWrapper) GetSubtitle(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	// ------------- Path parameter "trackId" -------------
	var trackId string

	err = runtime.BindStyledParameterWithOptions("simple", "trackId", r.PathValue("trackId"), &trackId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "trackId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSubtitleParams

	// ------------- Optional query parameter "token" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "token", r.URL.Query(), &params.Token, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "token"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSubtitle(w, r, itemId, trackId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartTranscode operation middleware
func (siw *ServerInterfaceWrapper) StartTranscode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartTranscode(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetWatched operation middleware
func (siw *ServerInterfaceWrapper) SetWatched(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", r.PathValue("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetWatched(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListLibraries operation middleware
func (siw *ServerInterfaceWrapper) ListLibraries(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLibraries(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMovies operation middleware
func (siw *ServerInterfaceWrapper) ListMovies(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "libraryId" -------------
	var libraryId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "libraryId", r.PathValue("libraryId"), &libraryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "libraryId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMoviesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tag", r.URL.Query(), &params.Tag, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tag"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMovies(w, r, libraryId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSeries operation middleware
func (siw *ServerInterfaceWrapper) ListSeries(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "libraryId" -------------
	var libraryId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "libraryId", r.PathValue("libraryId"), &libraryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "libraryId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSeriesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tag", r.URL.Query(), &params.Tag, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tag"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSeries(w, r, libraryId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Ping operation middleware
func (siw *ServerInterfaceWrapper) Ping(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Ping(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRecent operation middleware
func (siw *ServerInterfaceWrapper) ListRecent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRecentParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRecent(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerScan operation middleware
func (siw *ServerInterfaceWrapper) TriggerScan(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerScan(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetScanStatus operation middleware
func (siw *ServerInterfaceWrapper) GetScanStatus(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetScanStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSeries operation middleware
func (siw *ServerInterfaceWrapper) GetSeries(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "seriesId" -------------
	var seriesId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "seriesId", r.PathValue("seriesId"), &seriesId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "seriesId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSeries(w, r, seriesId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTranscodeCache operation middleware
func (siw *ServerInterfaceWrapper) GetTranscodeCache(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTranscodeCache(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTranscodeCapabilities operation middleware
func (siw *ServerInterfaceWrapper) GetTranscodeCapabilities(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTranscodeCapabilities(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTranscodeSessions operation middleware
func (siw *ServerInterfaceWrapper) ListTranscodeSessions(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTranscodeSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopTranscode operation middleware
func (siw *ServerInterfaceWrapper) StopTranscode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId string

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopTranscode(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTranscodeFile operation middleware
func (siw *ServerInterfaceWrapper) GetTranscodeFile(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId string

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	// ------------- Path parameter "file" -------------
	var file string

	err = runtime.BindStyledParameterWithOptions("simple", "file", r.PathValue("file"), &file, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "file", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTranscodeFile(w, r, sessionId, file)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/auth/devices", wrapper.ListDevices)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/auth/devices", wrapper.RegisterDevice)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/auth/devices/{deviceId}", wrapper.RevokeDevice)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/auth/devices/{deviceId}", wrapper.RenameDevice)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/auth/login", wrapper.Login)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/auth/me", wrapper.GetCurrentSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/continue", wrapper.ListContinue)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/items/{itemId}", wrapper.GetMediaItem)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/items/{itemId}/playback", wrapper.GetPlaybackInfo)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/items/{itemId}/progress", wrapper.GetProgress)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/api/v1/items/{itemId}/progress", wrapper.ReportProgress)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/items/{itemId}/stream", wrapper.StreamItem)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/items/{itemId}/subtitles", wrapper.ListSubtitles)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/items/{itemId}/subtitles/{trackId}", wrapper.GetSubtitle)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/items/{itemId}/transcode", wrapper.StartTranscode)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/items/{itemId}/watched", wrapper.SetWatched)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/libraries", wrapper.ListLibraries)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/libraries/{libraryId}/movies", wrapper.ListMovies)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/libraries/{libraryId}/series", wrapper.ListSeries)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/ping", wrapper.Ping)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/recent", wrapper.ListRecent)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/scan", wrapper.TriggerScan)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/scan/status", wrapper.GetScanStatus)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/series/{seriesId}", wrapper.GetSeries)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/transcode/cache", wrapper.GetTranscodeCache)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/transcode/capabilities", wrapper.GetTranscodeCapabilities)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/transcode/sessions", wrapper.ListTranscodeSessions)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/transcode/{sessionId}", wrapper.StopTranscode)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/transcode/{sessionId}/{file}", wrapper.GetTranscodeFile)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealth)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7D3pcts4mq/yFXerItXocBJndtZd88Odo5OaJO2ynekfrdQYIj9JaIMAGwClaFKu2ofYJ9wn2cJFkRKo",
	"w1cnU9N/2iJB4MN3X0C+JqnIC8GRa5WcfE0kqkJwhfbHGyHHNMuQmx+p4Bq5Nn+SomA0JZoKPvxNCfta",
	"pTPMifnrPyVOkpPkP4armYfurRq+llLI5ObmppdkqFJJCzNJcpKclnqGXJtZMYNxqYELDYQxscAsuekl",
	"H4V+I0qePTwo56hEKVO0EEzsmje95BMnpZ4JSf+JjwDDB6oU5VMQEiifE0YzSCVmBkOEqcR84OcwS5ym",
	"qSgdLIUUBUpNHQGpBXUiZE50cpKUJc2SXqKXBSYnidKS8qnZGyc5moFrL256icTfSyrNjn9N7Ld26Odq",
	"DjH+DVNt5ngpuKa8xHca801AslJa/FxgKnhmH/GSMTJmmJxoWWI1Iy/zMUoz457AX1PHFBsvCpSpp9DG",
	"3IVQdA2e2BiN8pNkW6BdraZQUlTvojDv+fEl1Qz3WkyHkRtvlkjkliko1zg124vR1mIyTL6JoxVGY/R/",
	"hXOa4iblU4lGpE91AzEZ0djXNMcYRfckPCNKXyDyLVPvRGQL5/eSghFtprTM2xDNl4wi1xAGDM2nwMgY",
	"GaSk0KXEDIgGiVOqtOP6wT6gSJyLa6yz8lgIhoSbl6VCeUveMp9+9Nts7uQVVQUjSzBIADEBPUMopJhQ",
	"hqBnVEFmaQpUwdioQdACOmbQG4aoQc3EQsFiJhRWIzVQ1d1ju62qpdrqCiG9Gg+1c955Dd/n+HuJKqIP",
	"HZgfW4lOlFoI2cRz9bB3T1zSwcF0AKNkgeNR0oNRoufu/8VMcBwl3R8sajlQDhW2B0kLaR1XNBe/3E1I",
	"M99OCTPz72cbqpG9Or4qUtbwvi8FnRvSRsJdhtVrI6MqxbXzX5oo+hGJRAn2LUyErOMpguu17Xogwuzb",
	"9mSw0sqP+yG31ea+LqgSGV6UeU7k8n6sLro5P7oHK9gqy7G3fs4xo8S4A7dUXBEbvSZjpZRWyByrP1Eg",
	"UZU5QvhyiyJabVjvbXUXRKczp6FbxlYaO6bfmpiN0tO6gxtkxPB4O5u4YbF539OxjDLIXV2sQx1HP1UU",
	"RjGl7Yr7YM18N9W1BcA2vURWPvg2xRRcdcPfjm0dITTmate3nxTKM/eRZVwHIZGSLDd2FcCpLRPb1Icg",
	"o69QE8oi7pvgmlCOci8JuY3CMcCdET2LMtgUuVzD0KYz3MDD3eMGMUc5p7jYa8eHBQkSzcTnFZ1irp4m",
	"0wM3/CjRQEWmjV14kLey1xmZRmSm2uJe7F9NFuxdBBWM5lTHrZaYTBS2vNNCExZ7tY4YC2cYH5ar5t6K",
	"glYrfec49yAW/EbZq5WFziiftmtdZUTVuYP4heQFc5BPhVrGcKg00aVqjhbXsZFzlIq6VM5qaIbzna5h",
	"gKhabDVXdHuMLC800Xg/3ts+eY2yyHZE5Id4Qjs8n80kQvi2DRtjkl6/4xMRMbFlRsVLkWG6F6c3TNem",
	"qaISU20WjKvhHPVMRGKrlzMkBSob2i3N+lAQPYP/+5//BUN6BKL6VPVAYkHSazJF6KSiWEJq4FbdHggJ",
	"EvvIzQPjoCIvcxtTWICses3LL4bPJOHKjKqhqm5KiE817kTEnGa4N97WI50Vmiqc1FEbpaIUU4lKfbKM",
	"9liMvYPxYoCeC6fYAglIllNuBJbiorG3FS4vUsK9O32OqmQuAZxldi3CzmobnRCmsLenL99zb1TcPjG3",
	"4rs7pXN7iUoJ5w2xbVPRqwUrzz18XEEaw6hBz0WlZJtbn1BO1eywVKCDgx7gJG8SKGLSZMm5WSEq+UoT",
	"eVDGcg13YfI69FFcWQludQt8uLj/zteyAbf3jJUFbFsGYN+YOWb4G7P3VtuMo8hgry022XM7D+jPu70c",
	"wJwNksd8rW/EOwtuWdjgFgfN0eg+HHw303fl3TdBvi2Hfp8e/E7X/QJV8KGjuZI9zZlLtu45WHqTvo3P",
	"rNnfWlTZrsZW4G+kuF3hwswfRUg5tki7lCS9jqW2J8R7FJtWaSJk2pYyoLEagFkDZoRnDH2CG+EXHP/9",
	"8hKQZ4WgXFelCMzHmGWYnTx3lQihTp4+e378YpR0B/HS2xjZ5ppvy5zwvkSSWcfYlTvC2spvHgqaXqNs",
	"mZdPS69J1vL1L8/6x/8FYYB1p1fg81HiPOtRUvJslMBihhxKfs3FgkdXciX+uvMXcGAEvkAewFURNzBq",
	"1tyEtT0ENFW061UUjjHHZXD3X5J0hsaJivhQ4zKbov5xqb1LFfiWcv3n46QXdR3n+Iq2OZbKiWj7AKsL",
	"919vDTO1r3sN2Jsr16DcgZmCjCmjVVa4qVXmhHolts49r220JcHElsgzBaWyHCq4q/vMhNLQIWxBlgoo",
	"T1mZoYJRosREL4hELwf7a1yFDFONLbU59OCkM6GQw3hpBSQVfEKntn5cSJygRJ4iCJlFhWVdJ1Wbry2+",
	"FZkhSos46kWT2Jko3cQbUZko9SXN8YNqQ3kGxmVmlK+KMkA55JQxqlxk1qhEtvOxKjCGTrcM2LdAFBDI",
	"S6ZpwWxFWyJhBgDoPBu8gL/+FZ4NXnzpNlZs29waflc7DaD0LJ62orjVAHoGaI8Do29oPP9HW0tskZJc",
	"PKnxywz1DH0R1EsmpKKgqHziAjo2LdFtpC8UdKokRbeey9gvhVEwsmRUae/4rHdhMaLpHOHT+fvQnPD2",
	"/QXYqiKET1elWw91VNkXNVbf5hhsykYIB9eDwVaJODh4dHnChiWyc7gIchVLGnAZapuKJ5RZBlRaFEVD",
	"zrdZKM8nvYr7agkdB8Nqs/WNNAlVw+Z23jfft9bzZjhPt7EhQuoaKFLCLbHh7eu/v4TO28GzP7/oGhUy",
	"+XB2PPxw8dpm3jLUVuPBnBKwGfcLa44HVF0uC7woi0KY3QzgF+MYWB8XCHeT+m4/qsCyLWY2Y0cx6wLR",
	"wB0XSlSClV5/GftA+RSO/waUK40kMxw6RvOsEg7bLmPgPYanR385KsyCWV12xARG5dHRc7SvPRgKNJFT",
	"1Ba0AbxyDoMyc9l8kkPBMQjOlt3BiCe9tgyGY8Emgi8Qr8GFMwaHXgNDx/slcLS3btwgfL04ec99iId4",
	"9VtKz61u+S8uI92Wrtw/2d2e2rYuQVpKqpcXBl7vzdkmlNPSFT+bpDpD2fdtO65JhSpVYmacBddahvJV",
	"1a1icWAhszOucDvTunD9pdSn1NcZgk36xvvBzGtWpSWS3HCyTWfLAVxa9VpgakTEevKUTxkGuTG6WZZ6",
	"NuLB0397eXlmvBktSap/sI9+En46MCZdTkiKVhzMOyuhFqYg9Mbj4lPkKG038ESKHKiGzlVOrhHCi6uu",
	"E6mX78BoRGW8uUzSifZi4YLe5NRWg+D07F2tFHOSHA2eDo6sD1MgJwVNTpLng6PBc9sGoGeWPkNS0OH8",
	"6ZCUejZ0xLDPpy7TYJjEJrKN9U3eU6Vf+TG9Zh/1s6Ojg1qG98qW1Fqcmo0AG83EP//NjDo+eto2ZQXs",
	"sNHlbLk2pDbs/nyDlAqtaanvwPERca07sBsSA8Y3NQz+2ec5Ypa+T2rd3woWVM+qKWttz5baY2o0FgGO",
	"C6jkwwAz4t6d9g0PPZCoS2nMJxAY1/u9SmW4SkggjJm4VBkzZY0NY8pxT5O25w2JS5zUo9I/imx5b83g",
	"7X2MN01FY8zXzQaLPX1QQHwBNsJdbnSllFy3/i2ZzavI5OTXz3XWC+gHEkhuiVf1OBq+sOpxNcA15m3w",
	"4E0vKtTDryF9c+P403paGyJ+bjtSKyYoiCQ5ajSx869fE8ptT5JtkXCWrJEUapCvVyPFruTT5w1SH0d6",
	"eQMVXM/s7UhgPnq++6PVsRD7xfHuL6rDG02V4vC5RjTojBKJmkp0ir9SKaMkrlSM0d1EyE/Ga6tmJjCR",
	"FHnGli4rNYDTLKdcQU6MPbUd0IQvq0ZZp968DvoBCLiSYH248cDMKCpBLHhca5iBfwi7PJx2qvez7qWX",
	"ju4ZhPiRHQPW98P2jt/WuM0y+W6VxcSUupSCt6Zrboh9/TA80OjRfGTiN9svd50g+8Ebf1WXY2cntIKq",
	"JfLeLVUdCBNg1le2+YrG8jtp7cKhqLv5E2rf/xyyTA+I/LDEgzmX5ya8nmPDqex45PVWHp0TmO7KMOw2",
	"86k/l7bVbw+H1x7FcW+clHs09z2s2rdBqnGKhyB4P8P0GizYVaEmbbbV17Dru0KaCLYfD7+67NLNNn6t",
	"WiH3MoZVuuo+Paf7E4n1zun7JNzdzIuFzNIUMgubC6hwMsHU5rJy1CQjmhxG2WHhm/O2kbjRwPcvQOXG",
	"fr4dEr+yXXl9mxhNQ1HMeK8ptan7IMrUCdtBVK7lylupHMb8i1DYNeB+O+StDjYxsuzb1Dx01o42dXfT",
	"uJcUpY4FsYWQfwwJ798jXWs1fWSfdCvvOJCyGhH/EF56i0TqMRJtCyVloVBqyzdrDHU/5n/o0sc15bGW",
	"b7avVcW4T5RPO9s8jrVT46XGviR8iqBc3QY6CvGa8ml3AMbBBqpG3B5WXs+RzymxU/ts3wxJhhJ+PgcC",
	"V3bEFfxeolyC5fneiCvKbSYa3l5+eP8CrmxBJrUN0642cwXIMPeVKC40KNQWCEMdd7g7Evm7bT6mq9Pb",
	"WT/oEKZR+nKWS5k28eRaHMy3Fkcr8IKTvYLmbgpapBp1f8UpkV2OKScycoRjU8zelIx5HgrL3fSSZ0d/",
	"jpRUiNSUsDAOOo7LvF7qPqZ4toSPdbteL8c4ybB1lYZkHCqcVU9Tm3yaYEitWrW0JOm1csXPOWagZ1KU",
	"05m/KYAKswdIZ4TyEwj9U6Dxix5x/2mnCtWqMwNdKFip4OcCeWiIU0a6Mpq59P8Mea0ZZjDir0k6c7A8",
	"UXBFsyugCiZoi21AVGhrq5ZSdMxMhBP63GIianZaLf+9ODL7tdE2ugwfMsC8m2U6DS1LG/xms/v8Nt5r",
	"xeHDr3auZkS6pg6kyMoUFXQIzyCj6rqfknSGqutSC7aBsuKuyvRA0/KM+K1MDzQtz4h702NXvYvp+Qkr",
	"tv7DbI/rPaXZSiJt7mut7fRq1XV61YOr0HN6tbJDTUg9QbeC+r2ZRaMrh3Otm2K+0+h5hRe4/bHEt5e8",
	"OHoWceqC+KaiZJm9NmtsLyAx4pV5auMXi2bm9Da4Hqbu9mTqmmJYCeOBWmHVhlZLm687pkRqBcS3KfQV",
	"zeyq7jvfurPKKIceOWvJqFbw9v3FiFddaZ/O3w/gHAu0FwFZ92KVX1Mkd84v/Cn04vwmXA1gxPELVdp1",
	"X7gVag1GqiALX852nTswmeQFTs1SDrQXR8+t+XTucei4UEBc4rnaTz/Mbo84QGdM0ut+YQKpUmI37tES",
	"qavmru88aow3qd346LEhsM8eYNH2ZLp/Bb75DoS0rHGnytbBEv78EW770xFeTElBUqMGmm6CpRF0PCq6",
	"1mS+v6jJZvg+7jXUWlC3aIhaj1e8rHaB2reJfee832x2+3fCZDN9TuR14CPwfAFDKHn4+5aJksZR1tZK",
	"1Ptq1GOECuFioMdtIquVZJ8oYLUd74fA4dfqePLNMBfzXTj94IbsI7f1c893cohjDmM4T7iaqDrx9eKo",
	"l+TkC83LPDl5dmR+Ue5+PY2dsokv4A8qRleoT3m0/5TKZRkiE1bn/0LbevhN/Ckqe7bw8x7hwhtqXHDj",
	"fLtCZEqkXBo/xzb2azL1LiThNMd2d5xM7zFHdctioD0G+2DS86MUC4XgWB4oBwJBUm4lO+7a0a2y4w64",
	"/lt2Hkl2biEzjojfodDUDo4/tMR4HB0iMYW/HyIqGWf+dM6D+Un1S49akLMlcL5wdxABtZ3TemnD19D6",
	"vtq3WirjKze2LTHcmRzNmZ1CyemEYgajhOOCLYFISeeYjRKY2CN4qRRKAc5RLgOqT0w8wzPCBEeYUJa7",
	"Tm5HlB5wXKDSMKFS6QGc+udP3MyE2ROEIe+WC2UiagOjiYhNUBsukHgC1vD0ibZfKE3yQvVACfPcRs08",
	"jLW1L3sIIUTzlj06GWZl4Q7ukHDKISUy64Ik/mAS4TaXZbPLJJ2FGQdgc9S+pHV1TblLUo8Sq6xHiTuc",
	"7BYaJW0J6XOH/bi23V8jPjuuacSnOzXio2Sld9/e9nC9ZQapbNm3/OF9jI7jwz952ncD49Z8010aQqVk",
	"Sx/mpaTTKcoLMyieVViXLDMfqAViAQui4PcSyzsF/v+9YxGqgDCJJFuCP2ZomDQs20Ch34wNi3JbmNIY",
	"pBsk9u2stm97XFLmjvV8IJxOUK21bbdicri6m62t7aR2udBDmqXVKg/XjOdCxyEjStdJUl0Ztx1d6Dy5",
	"cOX81qa7Axy46gr7b7VXp3Ed0LdTyHJgNZrt/L051s5VNxztIGuVqRraMtQ2ojbvinhIaYjdSvFgYlEt",
	"BhYDUCp7f96PhBlB6e7O6tVR2LwqYg9M1j54HITWFnwwlPqbLxRUF0Q0L70IhzDDnREgOB6CZ5983R5E",
	"rqe+Hye5tZlwf7ws1xw3E9SbHdbVscnLGcJbZPlBLP7Vz7vj0NqFFsVhhZtq3oNKrXsdU7vwNxb8IWpa",
	"iwJIpHBgZKAo5RRtPCFKXZT6loQYfp1Qhu09ByYyQ1dmtJ88sZVDIFLTCUm1OnFRDrGnHatyYueK8gy/",
	"DPLn5V+uur0RL1D250RS4ptEmW3b6Vy5bqF/fAwj7S0JQDnVoHCaGzyNuJmNajOoOA5nqH2zkR9Tm+kf",
	"H81/g/xYXXUHYPjUbNAwyohbB5KJRd8sj1m9dDqAOshV6dTVJ90/S1Hh306kNGUMws0X0OFitf2FpFoj",
	"hyXqbkvLQ8Xgbyh7SCbvRefy6f+7yMo2/Tfn2cD8xkFe4LR0t6VsgdFd+DrMi+M7d9cZ5qzoIGTgkEcv",
	"R7aVSduZxjDLeitsTdL8CeKgAjpO5IbrQtWzwtOrbX2bip4hYXr2z23+xls7JNmvMaRghK5Zvu33Vscq",
	"yjL80y8OumUrVk8hwwJ5hjxd+uShkdKMaDImCrtmjpKvLpraloEyFpCjMlQlGTV/QSHFGKPZp+Y8zWsx",
	"fv1shMVpFifLlv+TYWKe+7m+VkLt5jRi6p/YA2E3n2/+PwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
